"""
Lobbying — lobbying_2.py  (bold redesign)

Investigative lookup tool with three-path gateway.
Entry points: follow a politician · follow an organisation · browse by policy area.

Architecture:
- All data via DuckDB registered views (sql_views/lobbying_*.sql)
- Parquet generated by pipeline_sandbox/lobbying_enrichment.py
- No raw CSV/Parquet reads in this file
- No joins, groupby, or pivot in this file
- Two-stage flow: landing gateway → Stage 2 profile
"""
from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd
import streamlit as st

sys.path.insert(0, str(Path(__file__).parent.parent))

from data_access.lobbying_data import (
    fetch_all_org_names,
    fetch_all_politician_names,
    fetch_area_contact_detail,
    fetch_clients_for_org,
    fetch_contact_detail,
    fetch_dpo_returns_detail,
    fetch_org_contact_detail,
    fetch_org_index,
    fetch_org_persistence,
    fetch_orgs_for_politician,
    fetch_policy_area_summary,
    fetch_policy_exposure_for_politician,
    fetch_politician_index,
    fetch_politicians_for_area,
    fetch_politicians_for_org,
    fetch_recent_returns,
    fetch_revolving_door,
    fetch_summary,
)
from shared_css import inject_css
from ui.components import hero_banner, rank_card_row, todo_callout
from ui.export_controls import export_button

# ── State helpers ──────────────────────────────────────────────────────────────

def _init() -> None:
    for k, v in {
        "lob_selected_politician": None,
        "lob_selected_org":        None,
        "lob_selected_area":       None,
        "lob_selected_revdoor":    False,
        "lob_selected_dpo":        None,
        "lob_sidebar_search":      "",
        "lob_date_start":          None,
        "lob_date_end":            None,
    }.items():
        st.session_state.setdefault(k, v)


def _clear_profile() -> None:
    st.session_state.lob_selected_politician = None
    st.session_state.lob_selected_org        = None
    st.session_state.lob_selected_area       = None
    st.session_state.lob_selected_revdoor    = False
    st.session_state.lob_selected_dpo        = None


def _nav_pol(name: str) -> None:
    _clear_profile()
    st.session_state.lob_selected_politician = name


def _nav_org(name: str) -> None:
    _clear_profile()
    st.session_state.lob_selected_org = name


def _nav_area(area: str) -> None:
    _clear_profile()
    st.session_state.lob_selected_area = area


def _nav_revdoor() -> None:
    _clear_profile()
    st.session_state.lob_selected_revdoor = True


def _nav_dpo(name: str) -> None:
    st.session_state.lob_selected_dpo = name


# ── HTML helpers ───────────────────────────────────────────────────────────────

def _path_card_html(icon: str, heading: str, body: str, stat: str, stat_lbl: str) -> str:
    return (
        f'<div class="lob-path-card">'
        f'<div class="lob-path-icon">{icon}</div>'
        f'<p class="lob-path-heading">{heading}</p>'
        f'<p class="lob-path-body">{body}</p>'
        f'<div class="lob-path-stat">'
        f'<span class="lob-path-stat-num">{stat}</span>'
        f'<span class="lob-path-stat-lbl">&nbsp;{stat_lbl}</span>'
        f'</div></div>'
    )



def _activity_row_html(period: str, org: str, area: str) -> str:
    return (
        f'<div class="lob-activity-row">'
        f'<div class="lob-activity-period">{period or "—"}</div>'
        f'<div class="lob-activity-body">'
        f'<div class="lob-activity-org">{org or "—"}</div>'
        f'<div class="lob-activity-area">{area or ""}</div>'
        f'</div></div>'
    )


def _section_heading(text: str) -> None:
    st.markdown(f'<p class="section-heading">{text}</p>', unsafe_allow_html=True)


def _back_button() -> None:
    if st.button("← Back to Lobbying", key="lob_back"):
        _clear_profile()
        st.rerun()


def _apply_year_filter(df: pd.DataFrame, key: str) -> pd.DataFrame:
    """Render a year radio above a detail table and return the filtered DataFrame."""
    if df.empty or "period_start_date" not in df.columns:
        return df
    try:
        years = sorted(
            df["period_start_date"].dropna().apply(
                lambda x: x.year if hasattr(x, "year") else int(str(x)[:4])
            ).unique(),
            reverse=True,
        )
    except Exception:
        return df
    if not years:
        return df
    options = ["All"] + [str(y) for y in years]
    chosen = st.radio("Year", options, horizontal=True, key=key, label_visibility="collapsed")
    if chosen != "All":
        df = df[df["period_start_date"].apply(
            lambda x: (x.year if hasattr(x, "year") else int(str(x)[:4])) == int(chosen)
        )]
    return df


def _provenance_footer(summary: pd.DataFrame | pd.Series) -> None:
    with st.expander("About & data provenance", expanded=False):
        st.markdown(
            "**Data source:** lobbying.ie — the Irish Register of Lobbying. "
            "Returns are filed quarterly by organisations lobbying Designated Public Officials (DPOs). "
            "Data is extracted via the lobbying.ie API and processed by the Dáil Tracker pipeline."
        )
        st.divider()
        if not isinstance(summary, pd.Series):
            summary = summary.iloc[0] if not summary.empty else pd.Series()
        src = summary.get("source_summary", "lobbying.ie via lobby_processing.py")
        ts  = summary.get("latest_fetch_timestamp_utc", "—")
        fp  = summary.get("first_period", "—")
        lp  = summary.get("last_period",  "—")
        st.caption(f"Source: {src}")
        st.caption(f"Dataset covers: {fp} → {lp}  ·  Last fetched: {ts}")


# ── Sidebar ────────────────────────────────────────────────────────────────────

def _render_sidebar() -> None:
    with st.sidebar:
        st.markdown('<p class="lob-sidebar-label">Search</p>', unsafe_allow_html=True)
        search = st.text_input(
            "Search",
            placeholder="e.g. Ibec, Mary Lou McDonald",
            key="lob_sidebar_search",
            label_visibility="collapsed",
        )

        pol_names = fetch_all_politician_names()
        org_names = fetch_all_org_names()

        s = search.strip().lower()
        if s:
            pol_filtered = [n for n in pol_names if s in n.lower()]
            org_filtered = [n for n in org_names if s in n.lower()]
        else:
            pol_filtered = pol_names[:200]
            org_filtered = []

        combined_labels = (
            [""] +
            pol_filtered +
            [f"[Org] {n}" for n in org_filtered[:50]]
        )

        sel = st.selectbox(
            "Browse all members",
            combined_labels,
            label_visibility="collapsed",
        )
        if sel:
            if sel.startswith("[Org] "):
                _nav_org(sel[6:])
            else:
                _nav_pol(sel)
            st.rerun()

        st.divider()

        st.markdown('<p class="lob-sidebar-label">Notable targets</p>', unsafe_allow_html=True)
        notable = ["An Taoiseach", "Minister for Finance", "Tánaiste", "Minister for Health"]
        chip_cols = st.columns(2)
        for i, chip in enumerate(notable):
            if chip_cols[i % 2].button(chip, key=f"lob_chip_{i}", use_container_width=True):
                idx = fetch_politician_index()
                if not idx.empty and "position" in idx.columns:
                    m = idx[idx["position"].str.contains(chip, case=False, na=False)]
                    if not m.empty:
                        _nav_pol(m.iloc[0]["member_name"])
                        st.rerun()
                    else:
                        st.caption(f"No politician found with position matching '{chip}'.")

        areas = fetch_policy_area_summary()
        if not areas.empty and "public_policy_area" in areas.columns:
            st.divider()
            st.markdown('<p class="lob-sidebar-label">Browse by policy area</p>', unsafe_allow_html=True)
            top_areas = areas["public_policy_area"].dropna().head(10).tolist()
            for area in top_areas:
                safe_key = f"lob_area_{area[:25].replace(' ', '_')}"
                if st.button(area, key=safe_key, use_container_width=True):
                    _nav_area(area)
                    st.rerun()


# ── Landing page ───────────────────────────────────────────────────────────────

def _render_landing(summary: pd.DataFrame) -> None:
    s = summary.iloc[0] if not summary.empty else pd.Series()

    total_returns  = int(s.get("total_returns",      0) or 0)
    total_orgs     = int(s.get("total_orgs",         0) or 0)
    total_pols     = int(s.get("total_politicians",  0) or 0)
    total_areas    = int(s.get("total_policy_areas", 0) or 0)
    first_p        = s.get("first_period", "—")
    last_p         = s.get("last_period",  "—")

    hero_banner(
        kicker="LOBBYING REGISTER · IRELAND",
        title="Who is lobbying Irish politicians?",
        dek=(
            "Explore the official register of lobbying returns. "
            "Follow a politician to see who is lobbying them, "
            "follow an organisation to see who they target, "
            "or browse by policy area to understand where influence is concentrated."
        ),
        badges=[
            f"{total_returns:,} returns",
            f"{total_orgs:,} organisations",
            f"{total_pols:,} politicians",
            f"Data: {first_p} → {last_p}",
        ] if total_returns else [],
    )

    # Date range filter (global temporal control)
    with st.expander("Filter by date range", expanded=False):
        date_cols = st.columns(2)
        lob_start = date_cols[0].date_input(
            "From",
            value=st.session_state.lob_date_start,
            key="lob_date_start_input",
        )
        lob_end = date_cols[1].date_input(
            "To",
            value=st.session_state.lob_date_end,
            key="lob_date_end_input",
        )
        if date_cols[0].button("Apply", key="lob_apply_date"):
            st.session_state.lob_date_start = lob_start
            st.session_state.lob_date_end   = lob_end
            st.rerun()
        if date_cols[1].button("Clear", key="lob_clear_date"):
            st.session_state.lob_date_start = None
            st.session_state.lob_date_end   = None
            st.rerun()

    if summary.empty:
        st.info(
            "Enrichment pipeline not yet run. "
            "Run `python pipeline_sandbox/lobbying_enrichment.py` to populate data sections. "
            "Page structure shown below with placeholders.",
            icon="ℹ️",
        )

    # ── Four-path gateway (2 × 2) ─────────────────────────────────────────────
    _section_heading("Where do you want to investigate?")
    g1, g2 = st.columns(2)

    with g1:
        st.markdown(
            _path_card_html(
                "👤",
                "Follow a politician",
                "See every lobbying return targeting a specific politician or senator.",
                f"{total_pols:,}",
                "politicians on record",
            ),
            unsafe_allow_html=True,
        )
        if st.button("Browse politicians →", key="lob_gw_pol", use_container_width=True):
            idx = fetch_politician_index()
            if not idx.empty:
                _nav_pol(idx.iloc[0]["member_name"])
                st.rerun()

    with g2:
        st.markdown(
            _path_card_html(
                "🏢",
                "Follow an organisation",
                "See which politicians an organisation has lobbied and on what topics.",
                f"{total_orgs:,}",
                "organisations on record",
            ),
            unsafe_allow_html=True,
        )
        if st.button("Browse organisations →", key="lob_gw_org", use_container_width=True):
            orgs = fetch_org_index()
            if not orgs.empty:
                _nav_org(orgs.iloc[0]["lobbyist_name"])
                st.rerun()

    g3, g4 = st.columns(2)

    with g3:
        st.markdown(
            _path_card_html(
                "📋",
                "Browse by policy area",
                "Find all lobbying returns filed under a specific public policy area.",
                f"{total_areas:,}",
                "policy areas",
            ),
            unsafe_allow_html=True,
        )
        if st.button("Browse policy areas →", key="lob_gw_area", use_container_width=True):
            areas = fetch_policy_area_summary()
            if not areas.empty:
                _nav_area(areas.iloc[0]["public_policy_area"])
                st.rerun()

    with g4:
        dpos_preview = fetch_revolving_door()
        dpos_n = len(dpos_preview) if not dpos_preview.empty else 0
        st.markdown(
            _path_card_html(
                "🔄",
                "Revolving door",
                "Former politicians and senior officials who later filed lobbying returns.",
                f"{dpos_n:,}",
                "former DPOs identified",
            ),
            unsafe_allow_html=True,
        )
        if st.button("Browse revolving door →", key="lob_gw_revdoor", use_container_width=True):
            _nav_revdoor()
            st.rerun()

    st.write("")

    # ── Dual leaderboards ─────────────────────────────────────────────────────
    lb1, lb2 = st.columns(2)

    with lb1:
        _section_heading("Most-lobbied politicians")
        idx = fetch_politician_index()
        if idx.empty:
            todo_callout(
                "v_lobbying_index — run lobbying_enrichment.py to generate "
                "lobbying_politician_index.parquet"
            )
        else:
            for i, row in idx.head(10).iterrows():
                rank  = list(idx.index).index(i) + 1
                name  = str(row.get("member_name", "—"))
                meta  = " · ".join(filter(None, [
                    str(row.get("chamber",  "") or ""),
                    str(row.get("position", "") or ""),
                ]))
                pills = [
                    f"{int(row.get('return_count', 0) or 0):,} returns",
                    f"{int(row.get('distinct_orgs', 0) or 0):,} orgs",
                ]
                if rank_card_row(name, meta, pills, btn_key=f"lob_pol_{rank}", rank=rank):
                    _nav_pol(name)
                    st.rerun()

    with lb2:
        _section_heading("Most active organisations")
        orgs = fetch_org_index()
        if orgs.empty:
            todo_callout(
                "v_lobbying_org_index — run lobbying_enrichment.py to generate "
                "lobbying_org_index.parquet"
            )
        else:
            for i, row in orgs.head(10).iterrows():
                rank  = list(orgs.index).index(i) + 1
                name  = str(row.get("lobbyist_name", "—"))
                meta  = str(row.get("sector", "") or "")
                pills = [
                    f"{int(row.get('return_count', 0) or 0):,} returns",
                    f"{int(row.get('politicians_targeted', 0) or 0):,} politicians",
                ]
                if rank_card_row(name, meta, pills, btn_key=f"lob_org_{rank}", rank=rank):
                    _nav_org(name)
                    st.rerun()

    # ── Latest activity feed ──────────────────────────────────────────────────
    _section_heading("Latest returns")
    recent = fetch_recent_returns()
    if recent.empty:
        todo_callout(
            "v_lobbying_recent_returns — run lobbying_enrichment.py to generate "
            "lobbying_recent_returns.parquet"
        )
    else:
        activity_html = ""
        for _, row in recent.iterrows():
            period = str(row.get("period_start_date", "") or "")[:7]
            org    = str(row.get("lobbyist_name",     "") or "")
            area   = str(row.get("public_policy_area", "") or "")
            activity_html += _activity_row_html(period, org, area)
        st.markdown(activity_html, unsafe_allow_html=True)
        todo_callout(
            "member_name on v_lobbying_recent_returns — returns_master.csv is "
            "return-level, not politician-level; wire in once pipeline enrichment joins them"
        )

    st.write("")
    _provenance_footer(summary)


# ── Politician Stage 2 ─────────────────────────────────────────────────────────

def _render_politician(name: str, summary: pd.DataFrame) -> None:
    _back_button()

    idx = fetch_politician_index()
    pol_row = pd.Series()
    if not idx.empty and "member_name" in idx.columns:
        m = idx[idx["member_name"] == name]
        if not m.empty:
            pol_row = m.iloc[0]

    chamber  = str(pol_row.get("chamber",  "") or "")
    position = str(pol_row.get("position", "") or "")
    ret_cnt  = int(pol_row.get("return_count",        0) or 0)
    org_cnt  = int(pol_row.get("distinct_orgs",       0) or 0)
    area_cnt = int(pol_row.get("distinct_policy_areas", 0) or 0)
    first_p  = str(pol_row.get("first_period", "") or "")
    last_p   = str(pol_row.get("last_period",  "") or "")

    meta_badges = [b for b in [chamber, position] if b]
    hero_banner(
        kicker="LOBBYING PROFILE · POLITICIAN",
        title=name,
        dek=(
            f"Lobbied across {area_cnt} policy area(s) by {org_cnt} organisation(s). "
            f"Returns span {first_p} → {last_p}." if ret_cnt else
            "No lobbying returns on record for this politician."
        ),
        badges=meta_badges or None,
    )

    c1, c2, c3 = st.columns(3)
    c1.metric("Returns targeting them", f"{ret_cnt:,}")
    c2.metric("Distinct organisations", f"{org_cnt:,}")
    c3.metric("Policy areas",           f"{area_cnt:,}")

    # ── Orgs by intensity ─────────────────────────────────────────────────────
    _section_heading("Organisations lobbying this politician")
    intensity = fetch_orgs_for_politician(name)
    if intensity.empty:
        st.info("No intensity data available.")
    else:
        disp = intensity.rename(columns={
            "lobbyist_name":           "Organisation",
            "returns_in_relationship": "Returns",
            "distinct_policy_areas":   "Policy areas",
            "distinct_periods":        "Periods",
            "first_contact":           "First",
            "last_contact":            "Last",
        })
        st.dataframe(disp, use_container_width=True, hide_index=True)

    # ── Policy exposure ───────────────────────────────────────────────────────
    _section_heading("Policy areas lobbied on")
    exposure = fetch_policy_exposure_for_politician(name)
    if not exposure.empty:
        disp2 = exposure.rename(columns={
            "public_policy_area": "Policy area",
            "returns_targeting":  "Returns",
            "distinct_lobbyists": "Organisations",
        })
        st.dataframe(disp2, use_container_width=True, hide_index=True)

    # ── Lobbying returns ──────────────────────────────────────────────────────
    detail = fetch_contact_detail(name)
    _section_heading("Lobbying returns")
    if detail.empty:
        st.info("No lobbying contact detail on record for this politician.")
    else:
        detail = _apply_year_filter(detail, "lob_year_pol")
        display = detail[
            [c for c in ["period_start_date", "lobbyist_name",
                         "public_policy_area", "source_url"]
             if c in detail.columns]
        ].rename(columns={
            "period_start_date":  "Period",
            "lobbyist_name":      "Organisation",
            "public_policy_area": "Policy area",
            "source_url":         "Return URL",
        })
        st.dataframe(
            display,
            column_config={"Return URL": st.column_config.LinkColumn(
                "Return URL",
                display_text=r"https://www\.lobbying\.ie/return/(\d+)")},
            use_container_width=True,
            hide_index=True,
        )
        export_button(detail, "Export CSV", f"{name.replace(' ', '_')}_lobbying.csv",
                      "lob_export_pol_detail")

    st.write("")
    _provenance_footer(summary)


# ── Org Stage 2 ────────────────────────────────────────────────────────────────

def _render_org(org_name: str, summary: pd.DataFrame) -> None:
    _back_button()

    all_org_names = fetch_all_org_names()
    if all_org_names:
        picked = st.selectbox(
            "Switch organisation",
            all_org_names,
            index=all_org_names.index(org_name) if org_name in all_org_names else 0,
            key="lob_org_switcher",
        )
        if picked != org_name:
            _nav_org(picked)
            st.rerun()

    org_idx = fetch_org_index()
    org_row = pd.Series()
    if not org_idx.empty and "lobbyist_name" in org_idx.columns:
        m = org_idx[org_idx["lobbyist_name"] == org_name]
        if not m.empty:
            org_row = m.iloc[0]

    sector   = str(org_row.get("sector",               "") or "")
    website  = str(org_row.get("website",              "") or "")
    ret_cnt  = int(org_row.get("return_count",          0) or 0)
    pol_cnt  = int(org_row.get("politicians_targeted",  0) or 0)
    area_cnt = int(org_row.get("distinct_policy_areas", 0) or 0)
    first_p  = str(org_row.get("first_period", "") or "")
    last_p   = str(org_row.get("last_period",  "") or "")

    badges = [b for b in [sector] if b]
    if website and website.startswith("http"):
        badges.append(f'<a href="{website}" target="_blank" rel="noopener noreferrer" '
                      f'style="color:var(--dt-primary)">{website}</a>')

    hero_banner(
        kicker="LOBBYING PROFILE · ORGANISATION",
        title=org_name,
        dek=(
            f"Filed {ret_cnt:,} lobbying return(s) targeting {pol_cnt} politician(s) "
            f"across {area_cnt} policy area(s). Active {first_p} → {last_p}." if ret_cnt else
            "No lobbying returns on record for this organisation."
        ),
        badges=badges or None,
    )

    # ── Persistence stats ─────────────────────────────────────────────────────
    persist = fetch_org_persistence(org_name)
    if not persist.empty:
        pr = persist.iloc[0]
        c1, c2, c3, c4 = st.columns(4)
        c1.metric("Returns filed",       f"{ret_cnt:,}")
        c2.metric("Politicians targeted", f"{pol_cnt:,}")
        c3.metric("Periods filed",        str(pr.get("distinct_periods_filed", "—") or "—"))
        c4.metric("Active span (days)",   str(pr.get("active_span_days", "—") or "—"))
    else:
        c1, c2, c3 = st.columns(3)
        c1.metric("Returns filed",          f"{ret_cnt:,}")
        c2.metric("Politicians targeted",   f"{pol_cnt:,}")
        c3.metric("Policy areas",           f"{area_cnt:,}")

    # ── Politicians targeted (intensity) ─────────────────────────────────────
    _section_heading("Politicians targeted")
    pol_intensity = fetch_politicians_for_org(org_name)
    if pol_intensity.empty:
        st.info("No intensity data available.")
    else:
        disp = pol_intensity.rename(columns={
            "member_name":             "Politician",
            "chamber":                 "Chamber",
            "returns_in_relationship": "Returns",
            "distinct_policy_areas":   "Policy areas",
            "distinct_periods":        "Periods",
            "first_contact":           "First",
            "last_contact":            "Last",
        })
        st.dataframe(disp, use_container_width=True, hide_index=True)

    # ── Clients ───────────────────────────────────────────────────────────────
    clients = fetch_clients_for_org(org_name)
    if not clients.empty:
        _section_heading("Clients represented")
        disp_c = clients.rename(columns={
            "client_name":       "Client",
            "period_start_date": "Period",
            "policy_areas":      "Policy areas",
            "politicians_count": "Politicians",
            "source_url":        "Return URL",
        })
        st.dataframe(disp_c, use_container_width=True, hide_index=True)

    # ── All lobbying returns ──────────────────────────────────────────────────
    detail = fetch_org_contact_detail(org_name)
    _section_heading("All lobbying returns")
    if detail.empty:
        st.info("No lobbying contact detail on record for this organisation.")
    else:
        detail = _apply_year_filter(detail, "lob_year_org")
        display = detail[
            [c for c in ["period_start_date", "lobbyist_name", "member_name",
                         "public_policy_area", "source_url"]
             if c in detail.columns]
        ].rename(columns={
            "period_start_date":  "Period",
            "lobbyist_name":      "Organisation",
            "member_name":        "Politician",
            "public_policy_area": "Policy area",
            "source_url":         "Return URL",
        })
        st.dataframe(
            display,
            column_config={"Return URL": st.column_config.LinkColumn(
                "Return URL",
                display_text=r"https://www\.lobbying\.ie/return/(\d+)")},
            use_container_width=True,
            hide_index=True,
        )
        export_button(detail, "Export CSV",
                      f"{org_name[:40].replace(' ', '_')}_lobbying.csv",
                      "lob_export_org_detail")

    st.write("")
    _provenance_footer(summary)


# ── Area Stage 2 ────────────────────────────────────────────────────────────────

def _render_area(area: str, summary: pd.DataFrame) -> None:
    _back_button()

    areas_df  = fetch_policy_area_summary()
    area_row  = pd.Series()
    if not areas_df.empty:
        m = areas_df[areas_df["public_policy_area"] == area]
        if not m.empty:
            area_row = m.iloc[0]

    ret_cnt  = int(area_row.get("return_count",       0) or 0)
    org_cnt  = int(area_row.get("distinct_orgs",      0) or 0)
    pol_cnt  = int(area_row.get("distinct_politicians", 0) or 0)

    hero_banner(
        kicker="LOBBYING PROFILE · POLICY AREA",
        title=area,
        dek=(
            f"{ret_cnt:,} returns filed by {org_cnt} organisation(s) "
            f"targeting {pol_cnt} politician(s) on this topic." if ret_cnt else
            "No lobbying returns on record for this policy area."
        ),
    )

    c1, c2, c3 = st.columns(3)
    c1.metric("Returns",         f"{ret_cnt:,}")
    c2.metric("Organisations",   f"{org_cnt:,}")
    c3.metric("Politicians",     f"{pol_cnt:,}")

    # ── Most-exposed politicians ───────────────────────────────────────────────
    _section_heading("Most-targeted politicians")
    area_pols = fetch_politicians_for_area(area)
    if not area_pols.empty:
        disp = area_pols.rename(columns={
            "member_name":        "Politician",
            "chamber":            "Chamber",
            "returns_targeting":  "Returns",
            "distinct_lobbyists": "Organisations",
        })
        st.dataframe(disp, use_container_width=True, hide_index=True)

    # ── Lobbying returns ──────────────────────────────────────────────────────
    detail = fetch_area_contact_detail(area)
    _section_heading("Lobbying returns for this policy area")
    if detail.empty:
        st.info("No lobbying contact detail on record for this policy area.")
    else:
        detail = _apply_year_filter(detail, "lob_year_area")
        display = detail[
            [c for c in ["period_start_date", "lobbyist_name", "member_name", "source_url"]
             if c in detail.columns]
        ].rename(columns={
            "period_start_date": "Period",
            "lobbyist_name":     "Organisation",
            "member_name":       "Politician",
            "source_url":        "Return URL",
        })
        st.dataframe(
            display,
            column_config={"Return URL": st.column_config.LinkColumn(
                "Return URL",
                display_text=r"https://www\.lobbying\.ie/return/(\d+)")},
            use_container_width=True,
            hide_index=True,
        )
        export_button(detail, "Export CSV",
                      f"{area[:40].replace(' ', '_')}_lobbying.csv",
                      "lob_export_area_detail")

    st.write("")
    _provenance_footer(summary)


# ── Revolving door Stage 2 ────────────────────────────────────────────────────

def _render_revolving_door(summary: pd.DataFrame) -> None:
    _back_button()

    dpos = fetch_revolving_door()

    hero_banner(
        kicker="LOBBYING PROFILE · REVOLVING DOOR",
        title="Former DPOs on Lobbying Returns",
        dek=(
            f"{len(dpos):,} former Designated Public Officials identified on lobbying returns "
            f"by name-matching. Treat as indicative — linkage is approximate."
            if not dpos.empty else
            "No revolving door data available."
        ),
    )

    st.markdown(
        '<div class="lob-revolving-callout">'
        '<p class="lob-revolving-heading" style="margin:0 0 0.3rem">What is the revolving door?</p>'
        '<p style="font-size:0.85rem;color:#78350f;margin:0">'
        'Designated Public Officials (DPOs) — politicians, ministers, and senior officials — '
        'are subject to a one-year cooling-off period before they may lobby former colleagues. '
        'The individuals below were identified on lobbying.ie returns and cross-referenced '
        'against the DPO register by name. Match quality varies; no legal findings are implied.'
        '</p></div>',
        unsafe_allow_html=True,
    )

    if dpos.empty:
        todo_callout("v_lobbying_revolving_door — run lobbying_enrichment.py")
        return

    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Former DPOs identified", f"{len(dpos):,}")
    c2.metric("Total returns involved",
              f"{int(dpos['return_count'].sum()):,}")
    c3.metric("Distinct firms",
              f"{int(dpos['distinct_firms'].sum()):,}")
    c4.metric("Policy areas covered",
              f"{int(dpos['distinct_policy_areas'].sum()):,}")

    _section_heading("Individuals identified")
    list_col, _ = st.columns([3, 1])
    with list_col:
        for rank, (_, row) in enumerate(dpos.iterrows(), start=1):
            name     = str(row.get("individual_name", "—"))
            position = str(row.get("former_position", "") or "")
            chamber  = str(row.get("former_chamber",  "") or "").split("::")[0].strip()
            former   = ("Former " + position) if position else "Former DPO"
            meta     = " · ".join(filter(None, [former, chamber]))
            pills    = [
                f"{int(row.get('return_count', 0) or 0):,} returns",
                f"{int(row.get('distinct_firms', 0) or 0):,} firms",
                f"{int(row.get('distinct_politicians_targeted', 0) or 0):,} politicians targeted",
            ]
            if rank_card_row(name, meta, pills, btn_key=f"lob_dpo_{rank}"):
                _nav_dpo(name)
                st.rerun()

    st.write("")
    _provenance_footer(summary)


# ── DPO Stage 3 ────────────────────────────────────────────────────────────────

def _render_dpo(name: str, summary: pd.DataFrame) -> None:
    if st.button("← Back to Revolving Door", key="lob_back_dpo"):
        st.session_state.lob_selected_dpo = None
        st.rerun()

    dpos = fetch_revolving_door()
    dpo_row = pd.Series()
    if not dpos.empty:
        m = dpos[dpos["individual_name"] == name]
        if not m.empty:
            dpo_row = m.iloc[0]

    position = str(dpo_row.get("former_position", "") or "")
    chamber  = str(dpo_row.get("former_chamber",  "") or "").split("::")[0].strip()
    ret_cnt  = int(dpo_row.get("return_count",              0) or 0)
    firms    = int(dpo_row.get("distinct_firms",             0) or 0)
    pol_cnt  = int(dpo_row.get("distinct_politicians_targeted", 0) or 0)

    hero_banner(
        kicker="REVOLVING DOOR · INDIVIDUAL PROFILE",
        title=name,
        dek=(
            f"Former {position}" + (f", {chamber}" if chamber else "") +
            f". Identified on {ret_cnt:,} lobbying return(s) targeting "
            f"{pol_cnt:,} politician(s) across {firms:,} firm(s)."
        ) if position else f"Identified on {ret_cnt:,} lobbying return(s).",
        badges=[b for b in [position, chamber] if b] or None,
    )

    c1, c2, c3 = st.columns(3)
    c1.metric("Returns filed",        f"{ret_cnt:,}")
    c2.metric("Firms represented",    f"{firms:,}")
    c3.metric("Politicians targeted", f"{pol_cnt:,}")

    # ── All returns attributed to this DPO ───────────────────────────────────
    detail = fetch_dpo_returns_detail(name)
    if not detail.empty:
        detail = _apply_year_filter(detail, "lob_year_dpo_detail")
        _section_heading(f"Returns attributed · {len(detail):,} rows")
        disp = detail[
            [c for c in ["return_id", "period_start_date", "lobbyist_name",
                          "client_name", "public_policy_area", "source_url"]
             if c in detail.columns]
        ].rename(columns={
            "return_id":          "Return #",
            "period_start_date":  "Period",
            "lobbyist_name":      "Firm",
            "client_name":        "Client",
            "public_policy_area": "Policy area",
            "source_url":         "Return URL",
        })
        st.dataframe(
            disp,
            column_config={"Return URL": st.column_config.LinkColumn(
                "Return URL",
                display_text=r"https://www\.lobbying\.ie/return/(\d+)")},
            use_container_width=True,
            hide_index=True,
        )
        export_button(
            detail,
            label=f"Export CSV · {len(detail):,} rows",
            filename=f"{name.replace(' ', '_')}_dpo_returns.csv",
            key="lob_export_dpo",
        )
    else:
        st.info("No return detail found for this individual in the revolving door register.")

    st.write("")
    _provenance_footer(summary)


# ── Entry point ────────────────────────────────────────────────────────────────

def lobbying_page() -> None:
    _init()
    inject_css()

    _render_sidebar()

    summary  = fetch_summary()
    sel_pol  = st.session_state.lob_selected_politician
    sel_org  = st.session_state.lob_selected_org
    sel_area = st.session_state.lob_selected_area
    sel_rev  = st.session_state.lob_selected_revdoor
    sel_dpo  = st.session_state.lob_selected_dpo

    if sel_pol:
        _render_politician(sel_pol, summary)
    elif sel_org:
        _render_org(sel_org, summary)
    elif sel_area:
        _render_area(sel_area, summary)
    elif sel_dpo:
        _render_dpo(sel_dpo, summary)
    elif sel_rev:
        _render_revolving_door(summary)
    else:
        _render_landing(summary)


if __name__ == "__main__":
    lobbying_page()
