"""Curated current judiciary roster — name -> court (Courts Service, courts.ie/judges).

Extracted verbatim from the former pipeline_sandbox/probe_judiciary_join.py so the
throwaway probe could be deleted. This is hand-curated reference DATA (fetched
2026-06-04), the source of truth for extractors/persist_judiciary_data.py's current
roster + spine-to-roster elevation join. Re-curate by re-fetching courts.ie/judges.
"""

from __future__ import annotations

ROSTER = {
    "Supreme Court": [
        "Donal O'Donnell",
        "Iseult O'Malley",
        "Seamus Woulfe",
        "Gerard Hogan",
        "Brian Murray",
        "Maurice Collins",
        "Aileen Donnelly",
        "Niamh Hyland",
        "Brian O'Moore",
        "Caroline Costello",
        "David Barniville",
    ],
    "Court of Appeal": [
        "Caroline Costello",
        "John A. Edwards",
        "Máire Whelan",
        "Patrick J. McCarthy",
        "Isobel Kennedy",
        "Mary Faherty",
        "Ann Power",
        "Donald Binchy",
        "Teresa Pilkington",
        "Senan Allen",
        "Nuala Butler",
        "Charles Meenan",
        "Tara Burns",
        "Michael MacGrath",
        "Denis McDonald",
        "Anthony Michael Collins",
        "Alexander Owens",
    ],
    "High Court": [
        "David Barniville",
        "Paul McDermott",
        "Anthony Barr",
        "David Keane",
        "Max Barrett",
        "Brian Cregan",
        "Tony Hunt",
        "Carmel Stewart",
        "Tony O'Connor",
        "Richard Humphreys",
        "Michael Twomey",
        "Miriam O'Regan",
        "Paul Coffey",
        "Leonie Reynolds",
        "Eileen Creedon",
        "Michael Quinn",
        "Garrett Simons",
        "John Jordan",
        "Mark Sanfey",
        "Mary Rose Gearty",
        "Mark Heslin",
        "Paul Burns",
        "Siobhan Stack",
        "David Holland",
        "Cian Ferriter",
        "Emily Egan",
        "Caroline Biggs",
        "Karen O'Connor",
        "Conor Dignam",
        "Siobhán Phelan",
        "Marguerite Bolger",
        "Kerida Naidoo",
        "Eileen Roberts",
        "Melanie Greally",
        "Mícheál P. O'Higgins",
        "Rory Mulcahy",
        "Emily Farrell",
        "Liam Kennedy",
        "Siobhan Lankford",
        "Barry O'Donnell",
        "Oisín Quinn",
        "Nuala Jackson",
        "Conleth Bradley",
        "Denise Brett",
        "David Nolan",
        "Patrick McGrath",
        "Nessa Cahill",
        "Sara Phelan",
        "Sean Gillane",
        "Mark Dunne",
        "Micheál O'Connell",
        "Patricia Ryan",
    ],
    "Circuit Court": [
        "Patricia Ryan",
        "James O'Donohoe",
        "Martin E. Nolan",
        "Sarah Berkeley",
        "Pauline Codd",
        "Keenan Johnson",
        "Eugene O'Kelly",
        "Francis Comerford",
        "Elma Sheahan",
        "John Francis Aylmer",
        "Sinéad Ní Chúlacháin",
        "Brian O'Callaghan",
        "Cormac Quinn",
        "Mary O'Malley Costello",
        "Patrick Quinn",
        "Martina Baxter",
        "Eoin Garavan",
        "Kathryn Hutton",
        "John O'Connor",
        "Helen Boyle",
        "Mary Morrissey",
        "Colin Daly",
        "Orla Crowe",
        "Dara Hayes",
        "Catherine Staines",
        "Kenneth Connolly",
        "John Martin",
        "Elva Duffy",
        "Elizabeth Maguire",
        "Simon McAleese",
        "Dermot Sheehan",
        "Sinead Behan",
        "Geoffrey Shannon",
        "Gerard Meehan",
        "Jennifer O'Brien",
        "Fiona O'Sullivan",
        "Jonathan Dunphy",
        "Christopher Callan",
        "Catherine White",
        "Ronan Munro",
        "Roderick Maguire",
        "Sinéad McMullan",
        "Deirdre Browne",
        "Alec Gabbett",
        "Paula Murphy",
        "Cephas Power",
        "Paul Kelly",
    ],
    "District Court": [
        "Paul Kelly",
        "Anne Watkin",
        "Anthony J. Halpin",
        "David McHugh",
        "Brendan Toale",
        "Gráinne Malone",
        "John Hughes",
        "Treasa Kelly",
        "John Campbell",
        "Máire Conneely",
        "Conor Fottrell",
        "Michèle Finan",
        "Catherine Ghent",
        "Shalom Binchy",
        "Karen Dowling",
        "Áine Shannon",
        "Michael Ramsey",
        "Emile Daly",
        "Éiteáin Cunningham",
        "Sandra Murphy",
        "James Faughnan",
        "Raymond Finnegan",
        "Nicola Jane Andrews",
        "Fiona Lydon",
        "Marie Keane",
        "Bernadette Owens",
        "Eirinn McKiernan",
        "Adrian Harris",
        "Carol Anne Coolican",
        "Patricia Harney",
        "Andrew Cody",
        "David Kennedy",
        "David Waters",
        "Joanne Carroll",
        "Philip O'Leary",
        "William Aylmer",
        "Colm Roberts",
        "John O'Leary",
        "Geraldine Carthy",
        "John Cheatle",
        "Kevin Staunton",
        "Desmond Zaidan",
        "Gerard Furlong",
        "Alan Mitchell",
        "Deirdre Gearty",
        "John King",
        "Miriam A. Walsh",
        "John F. Brennan",
        "Brendan O'Reilly",
        "Patricia Cronin",
        "Vincent Deane",
        "Ciaran Liddy",
        "Susan Fay",
        "Monika Leech",
        "Stephanie Coggans",
        "Fiona Brennan",
        "Michael Connellan",
        "Catherine Hayden",
        "Mark O'Connell",
        "Peter White",
        "Áine Clancy",
        "Catherine Ryan",
        "Valerie Corcoran",
        "Elizabeth Healy",
        "Derek Cooney",
        "Edward Carroll",
        "Paula Cullinane",
        "Andrew Gubbins",
        "Tom MacSharry",
        "Mary McAveety",
        "Darach McCarthy",
    ],
}
