"""Completeness report for the council-minutes corpus (doc/EXTRACTION_QUALITY_CHECKLIST.md).

Captured plenary-minutes docs per council-year vs an EXPECTED cadence of ~11 plenary
meetings/year (monthly minus August, plus budget/AGM — [Indicative: general practice under
LGA 2001 standing orders, NOT checked per council]). Dates come from filename parsing
(decisions_extract._fname_date), so the table carries its own date-coverage number — a
council whose filenames don't parse shows as unknown-year, not falsely incomplete.

Writes COMPLETENESS.md with the R12 section markers (## Completeness, ## Recall — the
recall section points at RECALL_PROBE.md).
Usage: python completeness_table.py
"""
from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path

from extractors.council_decisions_extract import _fname_date  # moved to production 2026-08-01

HERE = Path(__file__).resolve().parent
EXPECTED_PER_YEAR = 11  # [Indicative] see module docstring
YEARS = ("2024", "2025", "2026")


def main() -> int:
    docs = [json.loads(l) for l in (HERE / "meetings_clean.jsonl").read_text(encoding="utf-8").splitlines() if l.strip()]
    plenary = [d for d in docs if d.get("doc_type") == "plenary_minutes"]
    for d in plenary:
        if d["local_authority"] == "Galway":
            d["local_authority"] = "Galway County"

    by = defaultdict(lambda: defaultdict(int))
    undated = defaultdict(int)
    for d in plenary:
        # meeting_date (page-text backfill, finish_pass.py) beats filename parsing
        date = d.get("meeting_date") or _fname_date(d.get("meeting", "") or d.get("url", ""))
        yr = date[:4] if date[:4].isdigit() else (date[-4:] if date[-4:].isdigit() else "")
        if yr in YEARS:
            by[d["local_authority"]][yr] += 1
        else:
            undated[d["local_authority"]] += 1

    councils = sorted(set(by) | set(undated))
    L = ["# Council-minutes corpus — completeness & recall report\n"]
    L.append("Auto-generated by completeness_table.py.\n")
    L.append("## Completeness\n")
    L.append(f"Denominator: ~{EXPECTED_PER_YEAR} plenary meetings/council/year "
             "[Indicative — assumed cadence, not checked against each council's calendar]. "
             "Capture % inherits Indicative (weakest link). undated = plenary docs whose "
             "filename yields no year — they may fill gaps shown here.\n")
    L.append("| council | " + " | ".join(f"{y} (of {EXPECTED_PER_YEAR})" for y in YEARS) + " | undated |")
    L.append("|---|" + "---|" * (len(YEARS) + 1))
    for la in councils:
        cells = " | ".join(str(by[la].get(y, 0)) for y in YEARS)
        L.append(f"| {la} | {cells} | {undated.get(la, 0)} |")
    total_dated = sum(sum(v.values()) for v in by.values())
    total_undated = sum(undated.values())
    L.append(f"\nDate coverage: {total_dated}/{total_dated + total_undated} plenary docs "
             f"({100 * total_dated / max(1, total_dated + total_undated):.0f}%) carry a "
             "filename-parseable year in 2024-2026.\n")
    L.append("Known structural gaps: Dún Laoghaire-Rathdown (bespoke CMIS, no adapter), "
             "Mayo/Sligo (HTML/ASP.NET portals — agenda channel only via the June extractors), "
             "Cavan/Roscommon (seed pages expose few minutes PDFs).\n")
    L.append("## Recall\n")
    L.append("Power-event classifier recall is probed in RECALL_PROBE.md (strict vs broad "
             "nets + SVM-ranked gap docs). Golden-set per-class precision/recall lands in "
             "AB_COMPARISON.md. doc_type recall: unmeasured beyond the regex-label "
             "consistency exercise (CLASSIFIER_REPORT.md).\n")
    (HERE / "COMPLETENESS.md").write_text("\n".join(L), encoding="utf-8")
    print(f"completeness: {len(councils)} councils, {total_dated} dated + {total_undated} undated "
          f"plenary docs -> COMPLETENESS.md", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
