"""Independent verification of the Cork City (and Fingal) attributed member votes.

EXPERIMENTAL sandbox. The extractor's 4,341 Cork rows are UNVERIFIED beyond a 3-row
spot-check. Per the checklist (CoVe independence): this re-derives per-doc vote totals
with a DELIBERATELY DIFFERENT parser — split raw corpus text on FOR:/AGAINST:/ABSTAIN:
headers inside "appeared as follows" blocks, count comma-separated name tokens — and
compares doc-level totals against member_votes.jsonl grouped the same way. It never reads
the extractor's parsing code path; agreement is evidence, disagreement is a queue.

Checks per doc: (1) total FOR/AGAINST/ABSTAIN counts match; (2) block count matches the
extractor's motion count; (3) no member appears twice in one motion (extractor side).
Writes VOTE_VERIFICATION.md. Usage: python cork_vote_verify.py
"""
from __future__ import annotations

import json
import re
from collections import Counter, defaultdict
from pathlib import Path

HERE = Path(__file__).resolve().parent

_BLOCK = re.compile(r"appeared as follows", re.I)
_SECTION = re.compile(r"\b(FOR|AGAINST|ABSTAIN\w*)\s*:", re.I)
# a name token: optional initials + capitalised surname ("J. Maher", "M.R. Desmond",
# "T. Fitzgerald", "de Róiste" style kept loose)
_NAME = re.compile(r"[A-ZÁÉÍÓÚ][\w'’.]*\.?\s*(?:[A-ZÁÉÍÓÚ][\w'’.]*\.?\s*)?[A-ZÁÉÍÓÚa-záéíóú'’\-\w]+")
_STOP = re.compile(r"\b(Result|Motion|Item|The (Lord )?Mayor|An tArdmh|Proposed|Seconded|Comhairle)\b")


def independent_doc_tally(text: str) -> tuple[int, Counter]:
    """(n_vote_blocks, Counter{for/against/abstain: name_count}) from raw text."""
    tallies: Counter = Counter()
    blocks = 0
    marks = list(_BLOCK.finditer(text))
    for j, m in enumerate(marks):
        # segment ends at the NEXT block (or +4000) — overlapping segments double-counted
        # adjacent blocks in v1 and inflated dense docs (budget meetings)
        hard_end = marks[j + 1].start() if j + 1 < len(marks) else len(text)
        seg = text[m.end() : min(m.end() + 4000, hard_end)]
        sections = list(_SECTION.finditer(seg))
        if not sections:
            continue
        blocks += 1
        for i, s in enumerate(sections):
            start = s.end()
            end = sections[i + 1].start() if i + 1 < len(sections) else len(seg)
            body = seg[start:end]
            stop = _STOP.search(body)
            if stop:
                body = body[: stop.start()]
            # strip the honorific prefix then count comma-separated name tokens
            body = re.sub(r"Comhairleoir[íi]?|Councillors?|Cllrs?\.?", " ", body)
            # final pair is written "X and Y" / "X agus Y" — split it too, or one name
            # per section vanishes (the exact ext-ind == block-count residual of v2)
            parts = re.split(r",|\band\b|\bagus\b", body)
            names = [t for t in (p.strip(" .,\n") for p in parts) if _NAME.fullmatch(t or "")]
            key = s.group(1).lower()
            key = "abstain" if key.startswith("abstain") else key
            tallies[key] += len(names)
    return blocks, tallies


def main() -> int:
    votes = [json.loads(l) for l in (HERE / "member_votes.jsonl").read_text(encoding="utf-8").splitlines() if l.strip()]
    cork = [v for v in votes if v["local_authority"] == "Cork City"]
    by_doc: dict[str, Counter] = defaultdict(Counter)
    motions_per_doc: dict[str, set] = defaultdict(set)
    double = 0
    seen_pairs = set()
    for v in cork:
        by_doc[v["meeting"]][{"for": "for", "against": "against", "abstain": "abstain"}.get(v["vote"], v["vote"])] += 1
        motions_per_doc[v["meeting"]].add(v.get("motion", ""))
        pair = (v["meeting"], v.get("motion", ""), v["member"])
        if pair in seen_pairs:
            double += 1
        seen_pairs.add(pair)

    agree = mismatch = missing = 0
    rows = []
    for doc, ext in sorted(by_doc.items()):
        p = HERE / "corpus" / "cork_city" / doc
        if not p.exists():
            p2 = list((HERE / "corpus" / "cork_city").glob(doc.replace(".txt", "") + "*"))
            p = p2[0] if p2 else p
        if not p.exists():
            missing += 1
            continue
        blocks, ind = independent_doc_tally(p.read_text(encoding="utf-8", errors="replace"))
        ok = all(abs(ext.get(k, 0) - ind.get(k, 0)) <= max(1, round(0.02 * max(ext.get(k, 0), ind.get(k, 0)))) for k in ("for", "against", "abstain"))
        rows.append((doc[:55], blocks, len(motions_per_doc[doc]),
                     ext.get("for", 0), ind.get("for", 0), ext.get("against", 0), ind.get("against", 0), ok))
        agree += ok
        mismatch += (not ok)

    L = ["# Cork City member-vote verification (independent re-derivation)\n"]
    L.append(f"Auto-generated by cork_vote_verify.py. {len(cork):,} extractor rows across "
             f"{len(by_doc)} docs; independent parser = FOR/AGAINST name-token counts from raw "
             "corpus text (never touches the extractor's code path). Agreement tolerance: "
             "±max(1, 2%) per section per doc.\n")
    L.append(f"**Docs agreeing: {agree}/{agree + mismatch}** (missing corpus file: {missing}; "
             f"double-attributed member-motion pairs on the extractor side: {double}).\n")
    L.append("| doc | blocks(ind) | motions(ext) | for ext/ind | against ext/ind | ok |")
    L.append("|---|---|---|---|---|---|")
    for d, b, mo, fe, fi, ae, ai, ok in rows:
        L.append(f"| {d} | {b} | {mo} | {fe}/{fi} | {ae}/{ai} | {'✓' if ok else '✗'} |")
    (HERE / "VOTE_VERIFICATION.md").write_text("\n".join(L), encoding="utf-8")
    print(f"cork docs: agree={agree} mismatch={mismatch} missing={missing} "
          f"double_attribution={double} -> VOTE_VERIFICATION.md", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
