"""Recall probe for the power-event classifier: strict nets vs broad nets + ML ranking.

EXPERIMENTAL sandbox. Per doc/EXTRACTION_QUALITY_CHECKLIST.md: proving a class is absent
needs a BROAD search, not the absence of a strict-pattern hit. For each power class this
runs BOTH nets over the full corpus:
  strict = the statute-anchored regex minutes_value_classify.py uses
  broad  = a deliberately loose synonym net (high recall, low precision)
The GAP (broad-hit but not strict-hit) bounds the strict net's missed-positive rate. A
per-class TF-IDF+LinearSVC model (positives = strict-hit docs, negatives = no-broad-hit
docs) then ranks each gap doc by decision score, so the likeliest TRUE misses surface
first for human/LLM verification (P(True), independent — the checklist's protocol).

Outputs: recall_gap.jsonl (ranked gap docs + snippet) · RECALL_PROBE.md (per-class table).
Usage: python recall_probe.py
"""
from __future__ import annotations

import json
import re
from pathlib import Path

from minutes_value_classify import POWER_EVENTS

HERE = Path(__file__).resolve().parent

BROAD = {
    "reserved_real_budget": r"\bbudget\b",
    "reserved_real_devplan": r"development plan|variation|zoning|rezon",
    "reserved_real_lpt": r"property tax|\blpt\b",
    "reserved_real_rates": r"\brates?\b|valuation",
    "reserved_veto_s183": r"disposal|dispose of",
    "reserved_veto_part8": r"part\s*(8|viii)\b|s(ection)?\.?\s*179",
    "reserved_super_matcontra": r"contraven",
    "exec_noted_mgmt": r"management report|chief executive",
    "exec_noted_annual": r"annual report",
    "requisition_s140": r"requisition",
}


def main() -> int:
    docs = [json.loads(l) for l in (HERE / "meetings_clean.jsonl").read_text(encoding="utf-8").splitlines() if l.strip()]
    texts, meta = [], []
    for d in docs:
        p = HERE / d.get("text_path", "")
        if d.get("text_path") and p.exists():
            texts.append(p.read_text(encoding="utf-8", errors="replace"))
            meta.append(d)
    print(f"corpus: {len(texts)} docs with text", flush=True)

    from sklearn.feature_extraction.text import TfidfVectorizer
    from sklearn.svm import LinearSVC

    vec = TfidfVectorizer(ngram_range=(1, 2), max_features=40000, sublinear_tf=True)
    X = vec.fit_transform(t[:40000] for t in texts)

    rows, table = [], []
    for cls, strict_pat in POWER_EVENTS.items():
        strict = re.compile(strict_pat, re.I)
        broad = re.compile(BROAD[cls], re.I)
        s_idx = [i for i, t in enumerate(texts) if strict.search(t)]
        b_idx = [i for i, t in enumerate(texts) if broad.search(t)]
        gap = sorted(set(b_idx) - set(s_idx))
        neg = [i for i in range(len(texts)) if i not in set(b_idx)]
        ranked = []
        if len(s_idx) >= 10 and len(neg) >= 10 and gap:
            y = [1] * len(s_idx) + [0] * len(neg)
            clf = LinearSVC(class_weight="balanced").fit(X[s_idx + neg], y)
            scores = clf.decision_function(X[gap])
            ranked = sorted(zip(gap, scores), key=lambda z: -z[1])
        else:
            ranked = [(i, 0.0) for i in gap]
        for i, score in ranked:
            m = broad.search(texts[i])
            snip = re.sub(r"\s+", " ", texts[i][max(0, m.start() - 70) : m.start() + 110])
            rows.append({
                "power_class": cls, "local_authority": meta[i]["local_authority"],
                "meeting": meta[i]["meeting"], "svm_score": round(float(score), 3),
                "snippet": snip,
            })
        table.append((cls, len(s_idx), len(b_idx), len(gap),
                      sum(1 for _, s in ranked if s > 0)))
        print(f"{cls}: strict={len(s_idx)} broad={len(b_idx)} gap={len(gap)} "
              f"svm_flagged={sum(1 for _, s in ranked if s > 0)}", flush=True)

    (HERE / "recall_gap.jsonl").write_text(
        "\n".join(json.dumps(r, ensure_ascii=False) for r in rows), encoding="utf-8")

    L = ["# Recall probe — strict vs broad nets over the power classes\n"]
    L.append(f"Auto-generated by recall_probe.py over {len(texts)} docs. gap = broad-hit docs the "
             "strict net missed (an UPPER bound on missed positives — the broad net is deliberately "
             "noisy). svm_flagged = gap docs a per-class LinearSVC (strict-hits vs no-broad-hit "
             "docs) scores as positive-side — verify these FIRST (P(True), independent read of the "
             "raw text; doc/EXTRACTION_QUALITY_CHECKLIST.md protocol).\n")
    L.append("| power class | strict | broad | gap | svm_flagged |\n|---|---|---|---|---|")
    for cls, s, b, g, f in table:
        L.append(f"| {cls} | {s} | {b} | {g} | {f} |")
    L.append("\nTop-ranked gap docs per class are in recall_gap.jsonl (svm_score desc).")
    (HERE / "RECALL_PROBE.md").write_text("\n".join(L), encoding="utf-8")
    print("-> recall_gap.jsonl, RECALL_PROBE.md", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
