"""
Lobbying data access layer.

Owns:
- DuckDB connection bootstrapped from sql_views/lobbying_*.sql
- All retrieval SQL for the lobbying page (SELECT / WHERE / ORDER BY / LIMIT only)

Forbidden here (same rules as Streamlit page files):
- JOIN, GROUP BY, HAVING, WINDOW in ad-hoc retrieval SQL
- CREATE VIEW / CREATE TABLE
- pandas groupby, merge, pivot
- Business metric definitions

Parquet files are generated by pipeline_sandbox/lobbying_enrichment.py.
If enrichment has not run, fetch functions return empty DataFrames gracefully.
"""
from __future__ import annotations

from pathlib import Path

import duckdb
import pandas as pd
import streamlit as st

_SQL_VIEWS = Path(__file__).resolve().parents[2] / "sql_views"


@st.cache_resource
def get_lobbying_conn() -> duckdb.DuckDBPyConnection:
    conn = duckdb.connect()
    for sql_file in sorted(_SQL_VIEWS.glob("lobbying_*.sql")):
        conn.execute(sql_file.read_text(encoding="utf-8"))
    return conn


def _safe(sql: str, params: list | None = None) -> pd.DataFrame:
    try:
        conn = get_lobbying_conn()
        return conn.execute(sql, params or []).df()
    except Exception:
        return pd.DataFrame()


# ── Summary ────────────────────────────────────────────────────────────────────

@st.cache_data(ttl=300)
def fetch_summary() -> pd.DataFrame:
    return _safe("SELECT * FROM v_lobbying_summary LIMIT 1")


# ── Politician index ────────────────────────────────────────────────────────────

@st.cache_data(ttl=300)
def fetch_politician_index() -> pd.DataFrame:
    return _safe(
        "SELECT member_name, chamber, position, return_count,"
        " distinct_orgs, distinct_policy_areas, first_period, last_period"
        " FROM v_lobbying_index ORDER BY return_count DESC"
    )


@st.cache_data(ttl=300)
def fetch_all_politician_names() -> list[str]:
    df = _safe("SELECT member_name FROM v_lobbying_index ORDER BY member_name")
    if df.empty:
        return []
    return df["member_name"].dropna().tolist()


# ── Org index ──────────────────────────────────────────────────────────────────

@st.cache_data(ttl=300)
def fetch_org_index() -> pd.DataFrame:
    return _safe(
        "SELECT lobbyist_name, sector, return_count, politicians_targeted,"
        " distinct_policy_areas, website, profile_url, first_period, last_period"
        " FROM v_lobbying_org_index ORDER BY return_count DESC"
    )


@st.cache_data(ttl=300)
def fetch_all_org_names() -> list[str]:
    df = _safe("SELECT lobbyist_name FROM v_lobbying_org_index ORDER BY lobbyist_name")
    if df.empty:
        return []
    return df["lobbyist_name"].dropna().tolist()


# ── Contact detail ─────────────────────────────────────────────────────────────

@st.cache_data(ttl=300)
def fetch_contact_detail(
    member_name: str,
    start: str | None = None,
    end: str | None = None,
) -> pd.DataFrame:
    if start and end:
        return _safe(
            "SELECT return_id, member_name, lobbyist_name, public_policy_area,"
            " period_start_date, source_url"
            " FROM v_lobbying_contact_detail"
            " WHERE member_name = ?"
            " AND period_start_date BETWEEN ? AND ?"
            " ORDER BY period_start_date DESC",
            [member_name, start, end],
        )
    return _safe(
        "SELECT return_id, member_name, lobbyist_name, public_policy_area,"
        " period_start_date, source_url"
        " FROM v_lobbying_contact_detail"
        " WHERE member_name = ?"
        " ORDER BY period_start_date DESC",
        [member_name],
    )


@st.cache_data(ttl=300)
def fetch_org_contact_detail(
    org_name: str,
    start: str | None = None,
    end: str | None = None,
) -> pd.DataFrame:
    if start and end:
        return _safe(
            "SELECT return_id, member_name, lobbyist_name, public_policy_area,"
            " period_start_date, source_url"
            " FROM v_lobbying_contact_detail"
            " WHERE lobbyist_name = ?"
            " AND period_start_date BETWEEN ? AND ?"
            " ORDER BY period_start_date DESC",
            [org_name, start, end],
        )
    return _safe(
        "SELECT return_id, member_name, lobbyist_name, public_policy_area,"
        " period_start_date, source_url"
        " FROM v_lobbying_contact_detail"
        " WHERE lobbyist_name = ?"
        " ORDER BY period_start_date DESC",
        [org_name],
    )


@st.cache_data(ttl=300)
def fetch_area_contact_detail(
    area: str,
    start: str | None = None,
    end: str | None = None,
) -> pd.DataFrame:
    if start and end:
        return _safe(
            "SELECT return_id, member_name, lobbyist_name, public_policy_area,"
            " period_start_date, source_url"
            " FROM v_lobbying_contact_detail"
            " WHERE public_policy_area = ?"
            " AND period_start_date BETWEEN ? AND ?"
            " ORDER BY period_start_date DESC",
            [area, start, end],
        )
    return _safe(
        "SELECT return_id, member_name, lobbyist_name, public_policy_area,"
        " period_start_date, source_url"
        " FROM v_lobbying_contact_detail"
        " WHERE public_policy_area = ?"
        " ORDER BY period_start_date DESC",
        [area],
    )


# ── Policy area summary ────────────────────────────────────────────────────────

@st.cache_data(ttl=300)
def fetch_policy_area_summary() -> pd.DataFrame:
    return _safe(
        "SELECT public_policy_area, return_count, distinct_orgs, distinct_politicians"
        " FROM v_lobbying_policy_area_summary ORDER BY return_count DESC"
    )


# ── Recent returns ─────────────────────────────────────────────────────────────

@st.cache_data(ttl=300)
def fetch_recent_returns() -> pd.DataFrame:
    return _safe(
        "SELECT period_start_date, lobbyist_name, public_policy_area,"
        " relevant_matter, source_url"
        " FROM v_lobbying_recent_returns ORDER BY period_start_date DESC LIMIT 20"
    )


# ── Revolving door ─────────────────────────────────────────────────────────────

@st.cache_data(ttl=300)
def fetch_revolving_door() -> pd.DataFrame:
    return _safe(
        "SELECT individual_name, former_position, former_chamber,"
        " return_count, distinct_firms, distinct_policy_areas,"
        " distinct_politicians_targeted"
        " FROM v_lobbying_revolving_door ORDER BY return_count DESC LIMIT 50"
    )


# ── DPO individual profile ────────────────────────────────────────────────────

@st.cache_data(ttl=300)
def fetch_dpo_returns(individual_name: str) -> pd.DataFrame:
    """Returns filed where the DPO appears directly as the lobbyist name."""
    return _safe(
        "SELECT return_id, member_name, public_policy_area,"
        " period_start_date, source_url"
        " FROM v_lobbying_contact_detail"
        " WHERE lobbyist_name = ?"
        " ORDER BY period_start_date DESC",
        [individual_name],
    )


@st.cache_data(ttl=300)
def fetch_dpo_clients(individual_name: str) -> pd.DataFrame:
    """Client companies the DPO has lobbied on behalf of."""
    return _safe(
        "SELECT client_name, period_start_date, policy_areas,"
        " politicians_count, source_url"
        " FROM v_lobbying_clients"
        " WHERE lobbying_firm = ?"
        " ORDER BY period_start_date DESC",
        [individual_name],
    )


@st.cache_data(ttl=300)
def fetch_dpo_returns_detail(individual_name: str) -> pd.DataFrame:
    """All returns attributed to this DPO from the revolving door register.
    Includes firm name, client name, policy area, and source URL.
    Works for DPOs who filed under a firm name (not just their own name).
    """
    return _safe(
        "SELECT return_id, period_start_date, lobbyist_name, client_name,"
        " public_policy_area, source_url"
        " FROM v_lobbying_dpo_returns"
        " WHERE individual_name = ?"
        " ORDER BY period_start_date DESC",
        [individual_name],
    )


# ── Source links ───────────────────────────────────────────────────────────────

@st.cache_data(ttl=300)
def fetch_sources_for_politician(member_name: str) -> pd.DataFrame:
    return _safe(
        "SELECT return_id, source_url, official_pdf_url, oireachtas_url"
        " FROM v_lobbying_sources WHERE member_name = ?"
        " ORDER BY return_id LIMIT 20",
        [member_name],
    )


@st.cache_data(ttl=300)
def fetch_sources_for_org(org_name: str) -> pd.DataFrame:
    return _safe(
        "SELECT return_id, source_url, official_pdf_url, oireachtas_url"
        " FROM v_lobbying_sources WHERE lobbyist_name = ?"
        " ORDER BY return_id LIMIT 20",
        [org_name],
    )


# ── Org intensity (bilateral relationships) ────────────────────────────────────

@st.cache_data(ttl=300)
def fetch_orgs_for_politician(member_name: str) -> pd.DataFrame:
    """Orgs that have lobbied a politician, ranked by intensity."""
    return _safe(
        "SELECT lobbyist_name, returns_in_relationship, distinct_policy_areas,"
        " distinct_periods, first_contact, last_contact"
        " FROM v_lobbying_org_intensity"
        " WHERE member_name = ?"
        " ORDER BY returns_in_relationship DESC LIMIT 20",
        [member_name],
    )


@st.cache_data(ttl=300)
def fetch_politicians_for_org(org_name: str) -> pd.DataFrame:
    """Politicians targeted by an org, ranked by intensity."""
    return _safe(
        "SELECT member_name, chamber, returns_in_relationship,"
        " distinct_policy_areas, distinct_periods, first_contact, last_contact"
        " FROM v_lobbying_org_intensity"
        " WHERE lobbyist_name = ?"
        " ORDER BY returns_in_relationship DESC LIMIT 20",
        [org_name],
    )


# ── Persistence ────────────────────────────────────────────────────────────────

@st.cache_data(ttl=300)
def fetch_org_persistence(org_name: str) -> pd.DataFrame:
    return _safe(
        "SELECT first_return_date, last_return_date, total_returns,"
        " distinct_periods_filed, active_span_days"
        " FROM v_lobbying_persistence WHERE lobbyist_name = ? LIMIT 1",
        [org_name],
    )


# ── Policy exposure ────────────────────────────────────────────────────────────

@st.cache_data(ttl=300)
def fetch_policy_exposure_for_politician(member_name: str) -> pd.DataFrame:
    """Policy areas a politician has been lobbied on, ranked by volume."""
    return _safe(
        "SELECT public_policy_area, returns_targeting, distinct_lobbyists"
        " FROM v_lobbying_policy_exposure"
        " WHERE member_name = ?"
        " ORDER BY returns_targeting DESC",
        [member_name],
    )


@st.cache_data(ttl=300)
def fetch_politicians_for_area(area: str) -> pd.DataFrame:
    """Politicians most exposed to a given policy area."""
    return _safe(
        "SELECT member_name, chamber, returns_targeting, distinct_lobbyists"
        " FROM v_lobbying_policy_exposure"
        " WHERE public_policy_area = ?"
        " ORDER BY returns_targeting DESC LIMIT 20",
        [area],
    )


# ── Clients ────────────────────────────────────────────────────────────────────

@st.cache_data(ttl=300)
def fetch_clients_for_org(org_name: str) -> pd.DataFrame:
    """Client companies represented by a lobbying firm."""
    return _safe(
        "SELECT client_name, period_start_date, policy_areas,"
        " politicians_count, source_url"
        " FROM v_lobbying_clients"
        " WHERE lobbying_firm = ?"
        " ORDER BY period_start_date DESC LIMIT 50",
        [org_name],
    )
