"""
Lobbying data access layer.

Owns:
- DuckDB connection bootstrapped from sql_views/lobbying_*.sql
- All retrieval SQL for the lobbying page (SELECT / WHERE / ORDER BY / LIMIT only)

Forbidden here (same rules as Streamlit page files):
- JOIN, GROUP BY, HAVING, WINDOW in ad-hoc retrieval SQL
- CREATE VIEW / CREATE TABLE
- pandas groupby, merge, pivot
- Business metric definitions

Parquet files are generated by pipeline_sandbox/lobbying_enrichment.py.
If enrichment has not run, fetch functions return empty DataFrames gracefully.
"""
from __future__ import annotations

from pathlib import Path

import duckdb
import pandas as pd
import streamlit as st


_SQL_VIEWS = Path(__file__).resolve().parents[2] / "sql_views"


@st.cache_resource
def get_lobbying_conn() -> duckdb.DuckDBPyConnection:
    conn = duckdb.connect()
    for sql_file in sorted(_SQL_VIEWS.glob("lobbying_*.sql")):
        conn.execute(sql_file.read_text(encoding="utf-8"))
    return conn


def _safe(sql: str, params: list | None = None) -> pd.DataFrame:
    try:
        conn = get_lobbying_conn()
        return conn.execute(sql, params or []).df()
    except Exception:
        return pd.DataFrame()


# ── Summary ────────────────────────────────────────────────────────────────────

@st.cache_data(ttl=300)
def fetch_summary() -> pd.DataFrame:
    return _safe("SELECT * FROM v_lobbying_summary LIMIT 1")


# ── Politician index ────────────────────────────────────────────────────────────

@st.cache_data(ttl=300)
def fetch_politician_index(year: int | None = None) -> pd.DataFrame:
    if year is not None:
        return _safe(
            "SELECT rank, member_name, unique_member_code, chamber, position, return_count,"
            " distinct_orgs, distinct_policy_areas, first_period, last_period"
            " FROM v_lobbying_index"
            " WHERE EXTRACT(YEAR FROM CAST(last_period AS DATE)) = ?"
            " ORDER BY return_count DESC",
            [year],
        )
    return _safe(
        "SELECT rank, member_name, unique_member_code, chamber, position, return_count,"
        " distinct_orgs, distinct_policy_areas, first_period, last_period"
        " FROM v_lobbying_index ORDER BY return_count DESC"
    )


@st.cache_data(ttl=300)
def fetch_all_politician_names() -> list[str]:
    df = _safe("SELECT member_name FROM v_lobbying_index ORDER BY member_name")
    if df.empty:
        return []
    return df["member_name"].dropna().tolist()


# ── Org index ──────────────────────────────────────────────────────────────────

@st.cache_data(ttl=300)
def fetch_org_index() -> pd.DataFrame:
    return _safe(
        "SELECT lobbyist_name, sector, return_count, politicians_targeted,"
        " distinct_policy_areas, website, profile_url, first_period, last_period"
        " FROM v_lobbying_org_index ORDER BY return_count DESC"
    )


@st.cache_data(ttl=300)
def fetch_all_org_names() -> list[str]:
    df = _safe("SELECT lobbyist_name FROM v_lobbying_org_index ORDER BY lobbyist_name")
    if df.empty:
        return []
    return df["lobbyist_name"].dropna().tolist()


# ── Contact detail ─────────────────────────────────────────────────────────────

@st.cache_data(ttl=300)
def fetch_contact_detail(
    member_name: str,
    start: str | None = None,
    end: str | None = None,
) -> pd.DataFrame:
    if start and end:
        return _safe(
            "SELECT return_id, member_name, lobbyist_name, public_policy_area,"
            " period_start_date, source_url"
            " FROM v_lobbying_contact_detail"
            " WHERE member_name = ?"
            " AND period_start_date BETWEEN ? AND ?"
            " ORDER BY period_start_date DESC",
            [member_name, start, end],
        )
    return _safe(
        "SELECT return_id, member_name, lobbyist_name, public_policy_area,"
        " period_start_date, source_url"
        " FROM v_lobbying_contact_detail"
        " WHERE member_name = ?"
        " ORDER BY period_start_date DESC",
        [member_name],
    )


@st.cache_data(ttl=300)
def fetch_org_contact_detail(
    org_name: str,
    start: str | None = None,
    end: str | None = None,
) -> pd.DataFrame:
    if start and end:
        return _safe(
            "SELECT return_id, member_name, lobbyist_name, public_policy_area,"
            " period_start_date, source_url"
            " FROM v_lobbying_contact_detail"
            " WHERE lobbyist_name = ?"
            " AND period_start_date BETWEEN ? AND ?"
            " ORDER BY period_start_date DESC",
            [org_name, start, end],
        )
    return _safe(
        "SELECT return_id, member_name, lobbyist_name, public_policy_area,"
        " period_start_date, source_url"
        " FROM v_lobbying_contact_detail"
        " WHERE lobbyist_name = ?"
        " ORDER BY period_start_date DESC",
        [org_name],
    )


@st.cache_data(ttl=300)
def fetch_politician_area_returns(
    member_name: str,
    area: str,
    start: str | None = None,
    end: str | None = None,
) -> pd.DataFrame:
    """Returns filed targeting one politician within one policy area."""
    if start and end:
        return _safe(
            "SELECT return_id, member_name, lobbyist_name, public_policy_area,"
            " period_start_date, source_url"
            " FROM v_lobbying_contact_detail"
            " WHERE member_name = ? AND public_policy_area = ?"
            " AND period_start_date BETWEEN ? AND ?"
            " ORDER BY period_start_date DESC",
            [member_name, area, start, end],
        )
    return _safe(
        "SELECT return_id, member_name, lobbyist_name, public_policy_area,"
        " period_start_date, source_url"
        " FROM v_lobbying_contact_detail"
        " WHERE member_name = ? AND public_policy_area = ?"
        " ORDER BY period_start_date DESC",
        [member_name, area],
    )


@st.cache_data(ttl=300)
def fetch_dpo_return_map() -> pd.DataFrame:
    """Map of return_id -> DPO individual_name (one row per match)."""
    return _safe(
        "SELECT return_id, individual_name FROM v_lobbying_dpo_returns"
    )


@st.cache_data(ttl=300)
def fetch_area_contact_detail(
    area: str,
    start: str | None = None,
    end: str | None = None,
) -> pd.DataFrame:
    if start and end:
        return _safe(
            "SELECT return_id, member_name, lobbyist_name, public_policy_area,"
            " period_start_date, source_url"
            " FROM v_lobbying_contact_detail"
            " WHERE public_policy_area = ?"
            " AND period_start_date BETWEEN ? AND ?"
            " ORDER BY period_start_date DESC",
            [area, start, end],
        )
    return _safe(
        "SELECT return_id, member_name, lobbyist_name, public_policy_area,"
        " period_start_date, source_url"
        " FROM v_lobbying_contact_detail"
        " WHERE public_policy_area = ?"
        " ORDER BY period_start_date DESC",
        [area],
    )


# ── Policy area summary ────────────────────────────────────────────────────────

@st.cache_data(ttl=300)
def fetch_policy_area_summary() -> pd.DataFrame:
    return _safe(
        "SELECT public_policy_area, return_count, distinct_orgs, distinct_politicians"
        " FROM v_lobbying_policy_area_summary ORDER BY return_count DESC"
    )


# ── Recent returns ─────────────────────────────────────────────────────────────

@st.cache_data(ttl=300)
def fetch_recent_returns() -> pd.DataFrame:
    return _safe(
        "SELECT period_start_date, lobbyist_name, public_policy_area,"
        " relevant_matter, source_url"
        " FROM v_lobbying_recent_returns ORDER BY period_start_date DESC LIMIT 20"
    )


# ── Revolving door ─────────────────────────────────────────────────────────────

@st.cache_data(ttl=300)
def fetch_revolving_door(limit: int | None = 50) -> pd.DataFrame:
    """Ranked DPO list for the landing callout (limit=5..7) and Stage 2a index (limit=None)."""
    if limit is None:
        return _safe(
            "SELECT individual_name, former_position, former_chamber, chamber_display,"
            " return_count, distinct_firms, distinct_policy_areas,"
            " distinct_politicians_targeted"
            " FROM v_lobbying_revolving_door ORDER BY return_count DESC"
        )
    return _safe(
        "SELECT individual_name, former_position, former_chamber, chamber_display,"
        " return_count, distinct_firms, distinct_policy_areas,"
        " distinct_politicians_targeted"
        " FROM v_lobbying_revolving_door ORDER BY return_count DESC LIMIT ?",
        [int(limit)],
    )


@st.cache_data(ttl=300)
def fetch_revolving_door_summary() -> pd.DataFrame:
    """Single-row aggregate for the landing callout headline number."""
    return _safe(
        "SELECT COUNT(*) AS individuals, SUM(return_count) AS total_returns,"
        " SUM(distinct_politicians_targeted) AS politicians_targeted_sum"
        " FROM v_lobbying_revolving_door"
    )


@st.cache_data(ttl=300)
def fetch_dpo_one(individual_name: str) -> pd.DataFrame:
    """Single DPO row for the Stage 2b individual hero."""
    return _safe(
        "SELECT individual_name, former_position, former_chamber, chamber_display,"
        " return_count, distinct_firms, distinct_policy_areas,"
        " distinct_politicians_targeted"
        " FROM v_lobbying_revolving_door WHERE individual_name = ? LIMIT 1",
        [individual_name],
    )


@st.cache_data(ttl=300)
def fetch_dpo_firms(individual_name: str) -> pd.DataFrame:
    """Firms a given DPO has filed returns under (Stage 2b: Firms represented)."""
    return _safe(
        "SELECT lobbyist_name, return_count, first_period, last_period"
        " FROM v_lobbying_dpo_firms"
        " WHERE individual_name = ?"
        " ORDER BY return_count DESC",
        [individual_name],
    )


@st.cache_data(ttl=300)
def fetch_dpo_client_breakdown(individual_name: str) -> pd.DataFrame:
    """Client companies a given DPO has lobbied on behalf of (Stage 2b: Clients represented)."""
    return _safe(
        "SELECT client_name, return_count, first_period, last_period"
        " FROM v_lobbying_dpo_clients"
        " WHERE individual_name = ?"
        " ORDER BY return_count DESC",
        [individual_name],
    )


@st.cache_data(ttl=300)
def fetch_dpo_politicians_targeted(individual_name: str) -> pd.DataFrame:
    """Politicians targeted by returns this DPO filed (Stage 2b: Politicians targeted)."""
    return _safe(
        "SELECT member_name, chamber, return_count"
        " FROM v_lobbying_dpo_politicians"
        " WHERE individual_name = ?"
        " ORDER BY return_count DESC",
        [individual_name],
    )


# ── DPO individual profile ────────────────────────────────────────────────────

@st.cache_data(ttl=300)
def fetch_dpo_returns(individual_name: str) -> pd.DataFrame:
    """Returns filed where the DPO appears directly as the lobbyist name."""
    return _safe(
        "SELECT return_id, member_name, public_policy_area,"
        " period_start_date, source_url"
        " FROM v_lobbying_contact_detail"
        " WHERE lobbyist_name = ?"
        " ORDER BY period_start_date DESC",
        [individual_name],
    )


@st.cache_data(ttl=300)
def fetch_dpo_clients(individual_name: str) -> pd.DataFrame:
    """Client companies the DPO has lobbied on behalf of."""
    return _safe(
        "SELECT client_name, period_start_date, policy_areas,"
        " politicians_count, source_url"
        " FROM v_lobbying_clients"
        " WHERE lobbying_firm = ?"
        " ORDER BY period_start_date DESC",
        [individual_name],
    )


@st.cache_data(ttl=300)
def fetch_dpo_returns_detail(individual_name: str) -> pd.DataFrame:
    """All returns attributed to this DPO from the revolving door register.
    Includes firm name, client name, policy area, and source URL.
    Works for DPOs who filed under a firm name (not just their own name).
    """
    return _safe(
        "SELECT return_id, period_start_date, lobbyist_name, client_name,"
        " public_policy_area, source_url"
        " FROM v_lobbying_dpo_returns"
        " WHERE individual_name = ?"
        " ORDER BY period_start_date DESC",
        [individual_name],
    )


# ── Source links ───────────────────────────────────────────────────────────────

@st.cache_data(ttl=300)
def fetch_sources_for_politician(member_name: str) -> pd.DataFrame:
    return _safe(
        "SELECT return_id, source_url, official_pdf_url, oireachtas_url"
        " FROM v_lobbying_sources WHERE member_name = ?"
        " ORDER BY return_id LIMIT 20",
        [member_name],
    )


@st.cache_data(ttl=300)
def fetch_sources_for_org(org_name: str) -> pd.DataFrame:
    return _safe(
        "SELECT return_id, source_url, official_pdf_url, oireachtas_url"
        " FROM v_lobbying_sources WHERE lobbyist_name = ?"
        " ORDER BY return_id LIMIT 20",
        [org_name],
    )


# ── Org intensity (bilateral relationships) ────────────────────────────────────

@st.cache_data(ttl=300)
def fetch_orgs_for_politician(member_name: str) -> pd.DataFrame:
    """Orgs that have lobbied a politician, ranked by intensity."""
    return _safe(
        "SELECT lobbyist_name, returns_in_relationship, distinct_policy_areas,"
        " distinct_periods, first_contact, last_contact"
        " FROM v_lobbying_org_intensity"
        " WHERE member_name = ?"
        " ORDER BY returns_in_relationship DESC LIMIT 20",
        [member_name],
    )


@st.cache_data(ttl=300)
def fetch_politicians_for_org(org_name: str) -> pd.DataFrame:
    """Politicians targeted by an org, ranked by intensity."""
    return _safe(
        "SELECT member_name, unique_member_code, chamber, returns_in_relationship,"
        " distinct_policy_areas, distinct_periods, first_contact, last_contact"
        " FROM v_lobbying_org_intensity"
        " WHERE lobbyist_name = ?"
        " ORDER BY returns_in_relationship DESC LIMIT 20",
        [org_name],
    )


# ── Persistence ────────────────────────────────────────────────────────────────

@st.cache_data(ttl=300)
def fetch_org_persistence(org_name: str) -> pd.DataFrame:
    return _safe(
        "SELECT first_return_date, last_return_date, total_returns,"
        " distinct_periods_filed, active_span_days"
        " FROM v_lobbying_persistence WHERE lobbyist_name = ? LIMIT 1",
        [org_name],
    )


# ── Policy exposure ────────────────────────────────────────────────────────────

@st.cache_data(ttl=300)
def fetch_policy_exposure_for_politician(member_name: str) -> pd.DataFrame:
    """Policy areas a politician has been lobbied on, ranked by volume."""
    return _safe(
        "SELECT public_policy_area, returns_targeting, distinct_lobbyists"
        " FROM v_lobbying_policy_exposure"
        " WHERE member_name = ?"
        " ORDER BY returns_targeting DESC",
        [member_name],
    )


@st.cache_data(ttl=300)
def fetch_politicians_for_area(area: str) -> pd.DataFrame:
    """Politicians most exposed to a given policy area."""
    return _safe(
        "SELECT member_name, unique_member_code, chamber, returns_targeting, distinct_lobbyists"
        " FROM v_lobbying_policy_exposure"
        " WHERE public_policy_area = ?"
        " ORDER BY returns_targeting DESC LIMIT 20",
        [area],
    )


# ── Clients ────────────────────────────────────────────────────────────────────

@st.cache_data(ttl=300)
def fetch_clients_for_org(org_name: str) -> pd.DataFrame:
    """Client companies represented by a lobbying firm."""
    return _safe(
        "SELECT client_name, period_start_date, policy_areas,"
        " politicians_count, source_url"
        " FROM v_lobbying_clients"
        " WHERE lobbying_firm = ?"
        " ORDER BY period_start_date DESC LIMIT 50",
        [org_name],
    )


# ── EXPERIMENTAL: lobbyist enrichment POC ─────────────────────────────────────
#
# Backed by v_experimental_lobbying_org_index_enriched (sql_views/
# lobbying_experimental_org_index_enriched.sql). Joins the lobbying gold
# leaderboard against pipeline_sandbox CRO + Charity silver outputs.
# Used exclusively by utility/pages_code/lobbyist_poc.py.

_EXPERIMENTAL_ORG_INDEX_COLS = (
    "lobbyist_name, return_count, politicians_targeted, distinct_policy_areas,"
    " first_period, last_period, rcn, company_num, sector_label, status,"
    " funding_profile, gov_funded_share_latest, gross_income_latest_eur,"
    " employees_band_latest, entity_age_years, newly_incorporated_flag,"
    " state_adjacent_flag, country_established, match_method, flags"
)


@st.cache_data(ttl=300)
def fetch_experimental_org_index_enriched(
    status: str | None = None,
    funding_profile: str | None = None,
    exclude_state_adjacent: bool = False,
    flagged_only: bool = False,
) -> pd.DataFrame:
    """Enriched lobbying-org leaderboard for the EXPERIMENTAL POC page.

    Only retrieval clauses are used here (WHERE / ORDER BY) — joins, modelling,
    and metric computation live in the SQL view.
    """
    where: list[str] = []
    params: list = []
    if status:
        where.append("status = ?")
        params.append(status)
    if funding_profile:
        where.append("funding_profile = ?")
        params.append(funding_profile)
    if exclude_state_adjacent:
        where.append("(state_adjacent_flag IS DISTINCT FROM TRUE)")
    if flagged_only:
        where.append("(flags IS NOT NULL AND len(flags) > 0)")
    where_sql = (" WHERE " + " AND ".join(where)) if where else ""
    return _safe(
        f"SELECT {_EXPERIMENTAL_ORG_INDEX_COLS}"
        f" FROM v_experimental_lobbying_org_index_enriched"
        f"{where_sql}"
        f" ORDER BY return_count DESC",
        params,
    )


@st.cache_data(ttl=300)
def fetch_experimental_org_index_summary() -> pd.DataFrame:
    """Single-row aggregate for the POC stat strip."""
    return _safe(
        "SELECT"
        " COUNT(*) AS total_orgs,"
        " COUNT(*) FILTER (WHERE match_method <> 'unmatched')      AS matched_orgs,"
        " COUNT(*) FILTER (WHERE match_method = 'both_name_exact') AS matched_both,"
        " COUNT(*) FILTER (WHERE state_adjacent_flag IS TRUE)      AS state_adjacent_orgs,"
        " COUNT(*) FILTER (WHERE newly_incorporated_flag IS TRUE)  AS newly_incorporated_orgs,"
        " COUNT(*) FILTER (WHERE funding_profile = 'state_funded') AS state_funded_orgs,"
        " COUNT(*) FILTER (WHERE flags IS NOT NULL AND len(flags) > 0) AS flagged_orgs"
        " FROM v_experimental_lobbying_org_index_enriched"
    )


@st.cache_data(ttl=300)
def fetch_experimental_org_one(org_name: str) -> pd.DataFrame:
    """Single enriched-index row for the Stage 2 detail hero."""
    return _safe(
        f"SELECT {_EXPERIMENTAL_ORG_INDEX_COLS}"
        f" FROM v_experimental_lobbying_org_index_enriched"
        f" WHERE lobbyist_name = ? LIMIT 1",
        [org_name],
    )


@st.cache_data(ttl=300)
def fetch_experimental_finance_timeseries(rcn: int) -> pd.DataFrame:
    """Annual-report finance time series for one charity (Stage 2 detail)."""
    return _safe(
        "SELECT period_year, period_end_date, gross_income, gross_expenditure,"
        " surplus_deficit, gov_share, gov_eur, other_public_bodies_eur,"
        " donations_eur, trading_eur, philanthropic_eur, other_income_eur,"
        " bequests_eur, cash_at_hand, total_assets, total_liabilities,"
        " net_assets, employees_band, volunteers_band"
        " FROM v_experimental_charity_finance_timeseries"
        " WHERE rcn = ? ORDER BY period_year DESC",
        [int(rcn)],
    )


@st.cache_data(ttl=300)
def fetch_experimental_returns_for_org(
    org_name: str,
    start: str | None = None,
    end: str | None = None,
) -> pd.DataFrame:
    """Returns filed by one organisation, with the lobbying.ie source URL.

    Reads v_lobbying_contact_detail directly — it is the canonical per-return
    view and already exposes source_url. Stage 2 needs no separate experimental
    view here.
    """
    if start and end:
        return _safe(
            "SELECT return_id, period_start_date, member_name,"
            " public_policy_area, source_url"
            " FROM v_lobbying_contact_detail"
            " WHERE lobbyist_name = ?"
            " AND period_start_date BETWEEN ? AND ?"
            " ORDER BY period_start_date DESC",
            [org_name, start, end],
        )
    return _safe(
        "SELECT return_id, period_start_date, member_name,"
        " public_policy_area, source_url"
        " FROM v_lobbying_contact_detail"
        " WHERE lobbyist_name = ?"
        " ORDER BY period_start_date DESC",
        [org_name],
    )


@st.cache_data(ttl=300)
def fetch_experimental_distinct_filters() -> dict[str, list[str]]:
    """Distinct values for the POC filter strip — status + funding_profile."""
    statuses = _safe(
        "SELECT DISTINCT status FROM v_experimental_lobbying_org_index_enriched"
        " WHERE status IS NOT NULL ORDER BY status"
    )
    profiles = _safe(
        "SELECT DISTINCT funding_profile FROM v_experimental_lobbying_org_index_enriched"
        " WHERE funding_profile IS NOT NULL ORDER BY funding_profile"
    )
    return {
        "status":          statuses["status"].tolist() if not statuses.empty else [],
        "funding_profile": profiles["funding_profile"].tolist() if not profiles.empty else [],
    }
