"""
Lobbying data access layer.

Owns:
- DuckDB connection bootstrapped from sql_views/lobbying_*.sql
- All retrieval SQL for the lobbying page (SELECT / WHERE / ORDER BY / LIMIT only)

Forbidden here (same rules as Streamlit page files):
- JOIN, GROUP BY, HAVING, WINDOW in ad-hoc retrieval SQL
- CREATE VIEW / CREATE TABLE
- pandas groupby, merge, pivot
- Business metric definitions

Parquet files are generated by pipeline_sandbox/lobbying_enrichment.py.
If enrichment has not run, fetch functions return empty DataFrames gracefully.
"""

from __future__ import annotations

from pathlib import Path

import duckdb
import pandas as pd
import streamlit as st

_PROJECT_ROOT = Path(__file__).resolve().parents[2]
_SQL_VIEWS = _PROJECT_ROOT / "sql_views"


def _absolutize_data_paths(sql: str) -> str:
    # SQL views use literals like read_parquet('data/silver/lobbying/...').
    # DuckDB resolves those against CWD, so a Streamlit launch from utility/
    # breaks queries. Rewrite to absolute project paths at registration time.
    return sql.replace("'data/", f"'{_PROJECT_ROOT.as_posix()}/data/")


@st.cache_resource
def get_lobbying_conn() -> duckdb.DuckDBPyConnection:
    conn = duckdb.connect()
    for sql_file in sorted(_SQL_VIEWS.glob("lobbying_*.sql")):
        conn.execute(_absolutize_data_paths(sql_file.read_text(encoding="utf-8")))
    return conn


def _safe(sql: str, params: list | None = None) -> pd.DataFrame:
    try:
        conn = get_lobbying_conn()
        return conn.execute(sql, params or []).df()
    except Exception:
        return pd.DataFrame()


# ── Summary ────────────────────────────────────────────────────────────────────


@st.cache_data(ttl=300)
def fetch_summary() -> pd.DataFrame:
    return _safe("SELECT * FROM v_lobbying_summary LIMIT 1")


# ── Return documents (embedded third-party PDFs) ───────────────────────────────


@st.cache_data(ttl=300)
def fetch_return_documents_for_org(org_name: str) -> pd.DataFrame:
    """Third-party PDF URLs embedded in this org's lobbying.ie returns.

    Sourced from v_lobbying_return_documents. These are lobbyist-supplied
    links to external hosts (position papers, pre-budget submissions, etc.)
    — distinct from Oireachtas-issued PDFs in v_legislation_pdfs.
    """
    return _safe(
        "SELECT return_id, lobby_url, source_field, pdf_url, host,"
        " date_published_timestamp, public_policy_area"
        " FROM v_lobbying_return_documents"
        " WHERE lobbyist_name = ?"
        " ORDER BY date_published_timestamp DESC NULLS LAST, return_id",
        [org_name],
    )


# ── Politician index ────────────────────────────────────────────────────────────


@st.cache_data(ttl=300)
def fetch_politician_index(year: int | None = None) -> pd.DataFrame:
    if year is not None:
        return _safe(
            "SELECT rank, member_name, unique_member_code, chamber, position, return_count,"
            " distinct_orgs, distinct_policy_areas, first_period, last_period"
            " FROM v_lobbying_index"
            " WHERE EXTRACT(YEAR FROM CAST(last_period AS DATE)) = ?"
            " ORDER BY return_count DESC",
            [year],
        )
    return _safe(
        "SELECT rank, member_name, unique_member_code, chamber, position, return_count,"
        " distinct_orgs, distinct_policy_areas, first_period, last_period"
        " FROM v_lobbying_index ORDER BY return_count DESC"
    )


@st.cache_data(ttl=300)
def fetch_all_politician_names() -> list[str]:
    df = _safe("SELECT member_name FROM v_lobbying_index ORDER BY member_name")
    if df.empty:
        return []
    return df["member_name"].dropna().tolist()


# ── Org index ──────────────────────────────────────────────────────────────────

# Full enrichment column set for the lobbying page (leaderboard + org profile).
# Drawn from v_experimental_lobbying_org_index_enriched — every charity-side
# column is null for orgs with no register match.
_ORG_INDEX_COLS = (
    "lobbyist_name, sector_label AS sector, return_count, politicians_targeted,"
    " distinct_policy_areas, first_period, last_period,"
    " rcn, company_num, status, match_method, entity_age_years,"
    " newly_incorporated_flag, state_adjacent_flag, country_established,"
    " trustee_count,"
    " funding_profile, gov_funded_share_latest, dominant_income_source,"
    " share_government, share_other_public, share_philanthropic,"
    " share_donations, share_trading, share_other, share_bequests,"
    " gross_income_latest_eur, gross_expenditure_latest_eur,"
    " employees_band_latest, employees_ft_latest, employees_pt_latest,"
    " volunteers_band_latest,"
    " surplus_deficit_latest, net_assets_latest_eur, cash_at_hand_latest_eur,"
    " total_assets_latest_eur, total_liabilities_latest_eur,"
    " reserves_months, reserves_band,"
    " income_trend, income_change_pct, years_filed,"
    " first_period_year, last_period_year, deficit_years_count,"
    " beneficiary_tags, report_activity_latest, flags"
)


@st.cache_data(ttl=300)
def fetch_org_index(exclude_state_adjacent: bool = False) -> pd.DataFrame:
    # Reads the CRO×Charity-enriched view so org cards/profiles can render the
    # full register enrichment. Row count is identical to v_lobbying_org_index
    # (same gold base); enrichment columns are null for unmatched orgs.
    #
    # exclude_state_adjacent drops HSE/hospital-type bodies — the leaderboard
    # passes it; the org switcher and Stage-2 lookup leave it False so any org
    # stays reachable.
    where = " WHERE (state_adjacent_flag IS DISTINCT FROM TRUE)" if exclude_state_adjacent else ""
    return _safe(
        f"SELECT {_ORG_INDEX_COLS} FROM v_experimental_lobbying_org_index_enriched{where} ORDER BY return_count DESC"
    )


@st.cache_data(ttl=300)
def fetch_all_org_names() -> list[str]:
    df = _safe("SELECT lobbyist_name FROM v_lobbying_org_index ORDER BY lobbyist_name")
    if df.empty:
        return []
    return df["lobbyist_name"].dropna().tolist()


# ── Contact detail ─────────────────────────────────────────────────────────────


@st.cache_data(ttl=300)
def fetch_contact_detail(
    member_name: str,
    start: str | None = None,
    end: str | None = None,
) -> pd.DataFrame:
    if start and end:
        return _safe(
            "SELECT return_id, member_name, lobbyist_name, public_policy_area,"
            " period_start_date, source_url"
            " FROM v_lobbying_contact_detail"
            " WHERE member_name = ?"
            " AND period_start_date BETWEEN ? AND ?"
            " ORDER BY period_start_date DESC",
            [member_name, start, end],
        )
    return _safe(
        "SELECT return_id, member_name, lobbyist_name, public_policy_area,"
        " period_start_date, source_url"
        " FROM v_lobbying_contact_detail"
        " WHERE member_name = ?"
        " ORDER BY period_start_date DESC",
        [member_name],
    )


@st.cache_data(ttl=300)
def fetch_org_contact_detail(
    org_name: str,
    start: str | None = None,
    end: str | None = None,
) -> pd.DataFrame:
    if start and end:
        return _safe(
            "SELECT return_id, member_name, lobbyist_name, public_policy_area,"
            " period_start_date, source_url"
            " FROM v_lobbying_contact_detail"
            " WHERE lobbyist_name = ?"
            " AND period_start_date BETWEEN ? AND ?"
            " ORDER BY period_start_date DESC",
            [org_name, start, end],
        )
    return _safe(
        "SELECT return_id, member_name, lobbyist_name, public_policy_area,"
        " period_start_date, source_url"
        " FROM v_lobbying_contact_detail"
        " WHERE lobbyist_name = ?"
        " ORDER BY period_start_date DESC",
        [org_name],
    )


@st.cache_data(ttl=300)
def fetch_politician_area_returns(
    member_name: str,
    area: str,
    start: str | None = None,
    end: str | None = None,
) -> pd.DataFrame:
    """Returns filed targeting one politician within one policy area."""
    if start and end:
        return _safe(
            "SELECT return_id, member_name, lobbyist_name, public_policy_area,"
            " period_start_date, source_url"
            " FROM v_lobbying_contact_detail"
            " WHERE member_name = ? AND public_policy_area = ?"
            " AND period_start_date BETWEEN ? AND ?"
            " ORDER BY period_start_date DESC",
            [member_name, area, start, end],
        )
    return _safe(
        "SELECT return_id, member_name, lobbyist_name, public_policy_area,"
        " period_start_date, source_url"
        " FROM v_lobbying_contact_detail"
        " WHERE member_name = ? AND public_policy_area = ?"
        " ORDER BY period_start_date DESC",
        [member_name, area],
    )


@st.cache_data(ttl=300)
def fetch_dpo_return_map() -> pd.DataFrame:
    """Map of return_id -> DPO individual_name (one row per match)."""
    return _safe("SELECT return_id, individual_name FROM v_lobbying_dpo_returns")


@st.cache_data(ttl=300)
def fetch_politician_area_returns_with_dpo(
    member_name: str,
    area: str,
    start: str | None = None,
    end: str | None = None,
) -> pd.DataFrame:
    """Returns filed for one politician × one policy area, pre-joined with
    DPO individual names ("; "-separated string) and a dpo_count column.

    Replaces the in-page dict-join in lobbying_2.py — the LEFT JOIN now
    lives in v_lobbying_contact_detail_with_dpo.
    """
    if start and end:
        return _safe(
            "SELECT return_id, member_name, lobbyist_name, public_policy_area,"
            " period_start_date, source_url, dpo_individuals, dpo_count"
            " FROM v_lobbying_contact_detail_with_dpo"
            " WHERE member_name = ? AND public_policy_area = ?"
            " AND period_start_date BETWEEN ? AND ?"
            " ORDER BY period_start_date DESC",
            [member_name, area, start, end],
        )
    return _safe(
        "SELECT return_id, member_name, lobbyist_name, public_policy_area,"
        " period_start_date, source_url, dpo_individuals, dpo_count"
        " FROM v_lobbying_contact_detail_with_dpo"
        " WHERE member_name = ? AND public_policy_area = ?"
        " ORDER BY period_start_date DESC",
        [member_name, area],
    )


@st.cache_data(ttl=300)
def fetch_area_contact_detail(
    area: str,
    start: str | None = None,
    end: str | None = None,
) -> pd.DataFrame:
    if start and end:
        return _safe(
            "SELECT return_id, member_name, lobbyist_name, public_policy_area,"
            " period_start_date, source_url"
            " FROM v_lobbying_contact_detail"
            " WHERE public_policy_area = ?"
            " AND period_start_date BETWEEN ? AND ?"
            " ORDER BY period_start_date DESC",
            [area, start, end],
        )
    return _safe(
        "SELECT return_id, member_name, lobbyist_name, public_policy_area,"
        " period_start_date, source_url"
        " FROM v_lobbying_contact_detail"
        " WHERE public_policy_area = ?"
        " ORDER BY period_start_date DESC",
        [area],
    )


# ── Policy area summary ────────────────────────────────────────────────────────


@st.cache_data(ttl=300)
def fetch_policy_area_summary() -> pd.DataFrame:
    return _safe(
        "SELECT public_policy_area, return_count, distinct_orgs, distinct_politicians"
        " FROM v_lobbying_policy_area_summary ORDER BY return_count DESC"
    )


# ── Topic keyword search ──────────────────────────────────────────────────────
#
# Free-text scan over relevant_matter + specific_details + intended_results.
# Backed by v_lobbying_topic_search (sql_views/lobbying_topic_search.sql).
# This is *not* a register taxonomy — see the view header for context.


def _topic_where(keywords: list[str]) -> tuple[str, list[str]]:
    """Build an OR-of-LIKE WHERE fragment for a list of keyword phrases."""
    cleaned = [k.strip().lower() for k in keywords if k and k.strip()]
    if not cleaned:
        return "", []
    clauses = " OR ".join(["searchable_text LIKE ?"] * len(cleaned))
    params = [f"%{k}%" for k in cleaned]
    return f"({clauses})", params


@st.cache_data(ttl=300)
def fetch_topic_returns(
    keywords: tuple[str, ...],
    start: str | None = None,
    end: str | None = None,
) -> pd.DataFrame:
    """Returns whose free-text description matches any of the keywords.

    Keywords are matched case-insensitively as substrings (no tokenisation).
    `keywords` is a tuple so the result can be cached.
    """
    where_kw, params = _topic_where(list(keywords))
    if not where_kw:
        return pd.DataFrame()
    sql = (
        "SELECT return_id, lobbyist_name, public_policy_area,"
        " relevant_matter, specific_details, intended_results,"
        " period_start_date, source_url"
        " FROM v_lobbying_topic_search"
        f" WHERE {where_kw}"
    )
    if start and end:
        sql += " AND period_start_date BETWEEN ? AND ?"
        params += [start, end]
    sql += " ORDER BY period_start_date DESC"
    return _safe(sql, params)


@st.cache_data(ttl=300)
def fetch_topic_summary(keywords: tuple[str, ...]) -> pd.DataFrame:
    """One-row aggregate for the Topic stage hero (counts, period span)."""
    where_kw, params = _topic_where(list(keywords))
    if not where_kw:
        return pd.DataFrame()
    return _safe(
        "SELECT COUNT(*) AS total_returns,"
        " COUNT(DISTINCT lobbyist_name) AS distinct_orgs,"
        " COUNT(DISTINCT public_policy_area) AS distinct_areas,"
        " MIN(period_start_date) AS first_period,"
        " MAX(period_start_date) AS last_period"
        " FROM v_lobbying_topic_search"
        f" WHERE {where_kw}",
        params,
    )


# ── Recent returns ─────────────────────────────────────────────────────────────


@st.cache_data(ttl=300)
def fetch_recent_returns() -> pd.DataFrame:
    return _safe(
        "SELECT period_start_date, lobbyist_name, public_policy_area,"
        " relevant_matter, source_url"
        " FROM v_lobbying_recent_returns ORDER BY period_start_date DESC LIMIT 20"
    )


# ── Revolving door ─────────────────────────────────────────────────────────────


@st.cache_data(ttl=300)
def fetch_revolving_door(limit: int | None = 50) -> pd.DataFrame:
    """Ranked DPO list for the landing callout (limit=5..7) and Stage 2a index (limit=None)."""
    if limit is None:
        return _safe(
            "SELECT individual_name, former_position, former_chamber, chamber_display,"
            " return_count, distinct_firms, distinct_policy_areas,"
            " distinct_politicians_targeted"
            " FROM v_lobbying_revolving_door ORDER BY return_count DESC"
        )
    return _safe(
        "SELECT individual_name, former_position, former_chamber, chamber_display,"
        " return_count, distinct_firms, distinct_policy_areas,"
        " distinct_politicians_targeted"
        " FROM v_lobbying_revolving_door ORDER BY return_count DESC LIMIT ?",
        [int(limit)],
    )


@st.cache_data(ttl=300)
def fetch_revolving_door_summary() -> pd.DataFrame:
    """Single-row aggregate for the landing callout headline number."""
    return _safe(
        "SELECT COUNT(*) AS individuals, SUM(return_count) AS total_returns,"
        " SUM(distinct_politicians_targeted) AS politicians_targeted_sum"
        " FROM v_lobbying_revolving_door"
    )


@st.cache_data(ttl=300)
def fetch_dpo_one(individual_name: str) -> pd.DataFrame:
    """Single DPO row for the Stage 2b individual hero."""
    return _safe(
        "SELECT individual_name, former_position, former_chamber, chamber_display,"
        " return_count, distinct_firms, distinct_policy_areas,"
        " distinct_politicians_targeted"
        " FROM v_lobbying_revolving_door WHERE individual_name = ? LIMIT 1",
        [individual_name],
    )


@st.cache_data(ttl=300)
def fetch_dpo_firms(individual_name: str) -> pd.DataFrame:
    """Firms a given DPO has filed returns under (Stage 2b: Firms represented)."""
    return _safe(
        "SELECT lobbyist_name, return_count, first_period, last_period"
        " FROM v_lobbying_dpo_firms"
        " WHERE individual_name = ?"
        " ORDER BY return_count DESC",
        [individual_name],
    )


@st.cache_data(ttl=300)
def fetch_dpo_client_breakdown(individual_name: str) -> pd.DataFrame:
    """Client companies a given DPO has lobbied on behalf of (Stage 2b: Clients represented)."""
    return _safe(
        "SELECT client_name, return_count, first_period, last_period"
        " FROM v_lobbying_dpo_clients"
        " WHERE individual_name = ?"
        " ORDER BY return_count DESC",
        [individual_name],
    )


@st.cache_data(ttl=300)
def fetch_dpo_politicians_targeted(individual_name: str) -> pd.DataFrame:
    """Politicians targeted by returns this DPO filed (Stage 2b: Politicians targeted)."""
    return _safe(
        "SELECT member_name, chamber, return_count"
        " FROM v_lobbying_dpo_politicians"
        " WHERE individual_name = ?"
        " ORDER BY return_count DESC",
        [individual_name],
    )


# ── DPO individual profile ────────────────────────────────────────────────────


@st.cache_data(ttl=300)
def fetch_dpo_returns(individual_name: str) -> pd.DataFrame:
    """Returns filed where the DPO appears directly as the lobbyist name."""
    return _safe(
        "SELECT return_id, member_name, public_policy_area,"
        " period_start_date, source_url"
        " FROM v_lobbying_contact_detail"
        " WHERE lobbyist_name = ?"
        " ORDER BY period_start_date DESC",
        [individual_name],
    )


@st.cache_data(ttl=300)
def fetch_dpo_clients(individual_name: str) -> pd.DataFrame:
    """Client companies the DPO has lobbied on behalf of."""
    return _safe(
        "SELECT client_name, period_start_date, policy_areas,"
        " politicians_count, source_url"
        " FROM v_lobbying_clients"
        " WHERE lobbying_firm = ?"
        " ORDER BY period_start_date DESC",
        [individual_name],
    )


@st.cache_data(ttl=300)
def fetch_dpo_returns_detail(individual_name: str) -> pd.DataFrame:
    """All returns attributed to this DPO from the revolving door register.
    Includes firm name, client name, policy area, and source URL.
    Works for DPOs who filed under a firm name (not just their own name).
    """
    return _safe(
        "SELECT return_id, period_start_date, lobbyist_name, client_name,"
        " public_policy_area, source_url"
        " FROM v_lobbying_dpo_returns"
        " WHERE individual_name = ?"
        " ORDER BY period_start_date DESC",
        [individual_name],
    )


# ── Source links ───────────────────────────────────────────────────────────────


@st.cache_data(ttl=300)
def fetch_sources_for_politician(member_name: str) -> pd.DataFrame:
    return _safe(
        "SELECT return_id, source_url, official_pdf_url, oireachtas_url"
        " FROM v_lobbying_sources WHERE member_name = ?"
        " ORDER BY return_id LIMIT 20",
        [member_name],
    )


@st.cache_data(ttl=300)
def fetch_sources_for_org(org_name: str) -> pd.DataFrame:
    return _safe(
        "SELECT return_id, source_url, official_pdf_url, oireachtas_url"
        " FROM v_lobbying_sources WHERE lobbyist_name = ?"
        " ORDER BY return_id LIMIT 20",
        [org_name],
    )


# ── Org intensity (bilateral relationships) ────────────────────────────────────


@st.cache_data(ttl=300)
def fetch_orgs_for_politician(member_name: str) -> pd.DataFrame:
    """Orgs that have lobbied a politician, ranked by intensity."""
    return _safe(
        "SELECT lobbyist_name, returns_in_relationship, distinct_policy_areas,"
        " distinct_periods, first_contact, last_contact"
        " FROM v_lobbying_org_intensity"
        " WHERE member_name = ?"
        " ORDER BY returns_in_relationship DESC LIMIT 20",
        [member_name],
    )


@st.cache_data(ttl=300)
def fetch_politicians_for_org(org_name: str) -> pd.DataFrame:
    """Politicians targeted by an org, ranked by intensity."""
    return _safe(
        "SELECT member_name, unique_member_code, chamber, returns_in_relationship,"
        " distinct_policy_areas, distinct_periods, first_contact, last_contact"
        " FROM v_lobbying_org_intensity"
        " WHERE lobbyist_name = ?"
        " ORDER BY returns_in_relationship DESC LIMIT 20",
        [org_name],
    )


# ── Persistence ────────────────────────────────────────────────────────────────


@st.cache_data(ttl=300)
def fetch_org_persistence(org_name: str) -> pd.DataFrame:
    return _safe(
        "SELECT first_return_date, last_return_date, total_returns,"
        " distinct_periods_filed, active_span_days"
        " FROM v_lobbying_persistence WHERE lobbyist_name = ? LIMIT 1",
        [org_name],
    )


# ── Policy exposure ────────────────────────────────────────────────────────────


@st.cache_data(ttl=300)
def fetch_policy_exposure_for_politician(member_name: str) -> pd.DataFrame:
    """Policy areas a politician has been lobbied on, ranked by volume."""
    return _safe(
        "SELECT public_policy_area, returns_targeting, distinct_lobbyists"
        " FROM v_lobbying_policy_exposure"
        " WHERE member_name = ?"
        " ORDER BY returns_targeting DESC",
        [member_name],
    )


@st.cache_data(ttl=300)
def fetch_politicians_for_area(area: str) -> pd.DataFrame:
    """Politicians most exposed to a given policy area."""
    return _safe(
        "SELECT member_name, unique_member_code, chamber, returns_targeting, distinct_lobbyists"
        " FROM v_lobbying_policy_exposure"
        " WHERE public_policy_area = ?"
        " ORDER BY returns_targeting DESC LIMIT 20",
        [area],
    )


# ── Clients ────────────────────────────────────────────────────────────────────


@st.cache_data(ttl=300)
def fetch_clients_for_org(org_name: str) -> pd.DataFrame:
    """Client companies represented by a lobbying firm."""
    return _safe(
        "SELECT client_name, period_start_date, policy_areas,"
        " politicians_count, source_url"
        " FROM v_lobbying_clients"
        " WHERE lobbying_firm = ?"
        " ORDER BY period_start_date DESC LIMIT 50",
        [org_name],
    )
