enrich_cols_to_select = ['join_key',
                  'unique_member_code',
                  'party', 
                  'first_name', 
                  'last_name', 
                  'member_constituency', 
                  'dail_term', 
                  'ministerial_office',
                  'committee_1_name_english',
                  'member_memberships_0_membership_committees_0_status',
                #   'committee_1_name_irish',
                  'committee_2_name_english',
                  'committee_2_status',
                  'committee_3_name_english',
                  'committee_3_status',
                  'committee_4_name_english',
                  'committee_4_status',
                  'committee_5_name_english',
                  'committee_5_status',
                #   'committee_4_service_unit'
                  
                  # ========== COPILOT EXPERIMENTAL: Phase 1 Committee Expansion ==========
                  # Adding standing order types to identify committee permanence (Statutory/Sessional)
                  'committee_1_standing_order_type',
                  'committee_2_standing_order_type',
                  # Adding committee codes for better filtering and analysis
                  # NOTE: These columns need flattened_members.csv to be regenerated with updated members_rename
                  # 'committee_1_code',
                  # 'committee_2_code',
                  # Adding Irish language committee names for multilingual coverage
                  'committee_1_name_irish',
                  'committee_2_name_irish',
                  ]


bill_cols_to_drop = [
    "bill_amendmentLists",
    "bill_act",
    "bill_billTypeURI",
    "bill_debates_0_chamber_uri",
    "bill_debates_0_debateSectionId",
    "bill_debates_0_uri",
    "bill_stages_0_event_chamber_uri",
    "bill_debates_1_chamber_uri",
    "bill_debates_2_chamber_uri",
    "bill_amendmentLists_5_amendmentList_chamber_uri",
    "bill_events_3_event_chamber_uri",
    "bill_stages_0_event_house_uri",
    "bill_debates_11_chamber_uri",
    "bill_debates_12_chamber_uri",
    "bill_stages_1_event_chamber_uri",
    "bill_amendmentLists_4_amendmentList_chamber_uri",
    "bill_debates_10_chamber_uri",
    "bill_amendmentLists_0_amendmentList_chamber_uri",
    "bill_amendmentLists_1_amendmentList_chamber_uri",
    "bill_amendmentLists_2_amendmentList_chamber_uri",
    "bill_amendmentLists_3_amendmentList_chamber_uri",
    "bill_stages_2_event_chamber_uri",
    "bill_stages_4_event_chamber_uri",
    "bill_debates_9_chamber_uri",
    "bill_debates_8_chamber_uri",
    "bill_debates_7_chamber_uri",
    "bill_debates_6_chamber_uri",
    "bill_debates_5_chamber_uri",
    "bill_debates_4_chamber_uri",
    "bill_debates_3_chamber_uri",
    "bill_events_0_event_chamber_chamberCode",
    "bill_events_0_event_chamber_showAs",
    "bill_events_0_event_chamber_uri",
    "bill_stages_2_event_house_uri",
    "bill_events_1_event_chamber_chamberCode",
    "bill_mostRecentStage_event_stageURI",
    "bill_mostRecentStage_event_uri",
    "bill_originHouse_uri",
    "bill_stages_9_event_house_uri",
    "bill_stages_8_event_house_uri",
    "bill_stages_3_event_house_uri",
    "bill_stages_1_event_house_uri",
    "bill_originHouseURI",
    "bill_sourceURI",
    "bill_sponsors_0_sponsor_as_showAs",
    "bill_versions_0_version_lang",
    "bill_versions_0_version_uri",
    "bill_stages_7_event_house_uri",
    "bill_debates_10_chamber_uri",
    "bill_stages_9_event_chamber_uri",
    "bill_events_2_event_chamber_uri",
    "bill_events_3_event_chamber_uri",
    "bill_events_1_event_chamber_uri",
    "bill_mostRecentStage_event_chamber_uri",
    "bill_debates_11_chamber_uri",
    "bill_debates_12_chamber_uri",
    "bill_stages_3_event_chamber_uri",
    "bill_stages_4_event_house_uri",
    "bill_stages_5_event_chamber_uri",
    "bill_stages_5_event_house_uri",
    "bill_stages_6_event_chamber_uri",
    "bill_stages_6_event_house_uri",
    "bill_stages_7_event_chamber_uri",
    "bill_stages_8_event_chamber_uri",
    "bill_events_0_event_eventURI",
    "bill_events_0_event_uri",
    "bill_events_1_event_eventURI",
    "bill_events_1_event_uri",
    "bill_methodURI",
    "bill_mostRecentStage_event_house_uri",
    "bill_stages_0_event_house_chamberCode",
    "bill_stages_0_event_house_chamberType",
    "bill_stages_0_event_house_houseCode",
    "bill_mostRecentStage_event_house_uri",
    "bill_relatedDocs_0_relatedDoc_lang",
    "bill_relatedDocs_0_relatedDoc_uri",
    "bill_sponsors_0_sponsor_as_uri",
    "bill_stages_0_event_stageURI",
    "bill_stages_0_event_uri",
    "bill_statusURI",
    "bill_versions_0_version_formats_xml",
    "bill_sponsors_2_sponsor_as_showAs",
    "bill_sponsors_2_sponsor_as_uri",
    "bill_sponsors_3_sponsor_as_showAs",
    "bill_sponsors_3_sponsor_as_uri",
    "bill_relatedDocs_0_relatedDoc_formats_xml"
]

bill_rename = {
    "bill_debates_0_chamber_showAs" : "bill_chamber",
    "bill_debates_0_date" : "bill_debates_date",
    "bill_debates_0_showAs" : "bill_debate_stages",
    "bill_events_0_event_chamber_showAs" : "bill_event_chamber",
    "bill_mostRecentStage_event_stageCompleted" : "bill_enacted",
    "bill_mostRecentStage_event_stageOutcome" : "bill_final_status",
    "bill_shortTitleEn" : "bill_short_title_en",
    "bill_shortTitleGa" : "bill_short_title_irish",
    "bill_sponsors_0_sponsor_by_showAs" : "bill_sponsor",
    "bill_sponsors_0_sponsor_by_uri" : "unique_member_code_raw",
    "bill_sponsors_0_sponsor_isPrimary" : "bill_primary_sponsor",
    "billSort_billShortTitleEnSort" : "bill_short_dash_title_en",
    "billSort_billShortTitleGaSort" : "bill_short_dash_title_irish",
    "billSort_billYearSort" : "bill_year",
    "bill_relatedDocs_0_relatedDoc_formats_pdf_uri" : "bill_related_doc_pdf",
    "bill_relatedDocs_0_relatedDoc_showAs" : "bill_related_doc_type",
    "bill_act_statutebookURI" : "bill_statue_book_link",
    "bill_billNo" : "bill_number",
    "bill_billYear" : "bill_year",
    "bill_lastUpdated" : "bill_date_last_updated",
    "bill_longTitleEn" : "bill_long_title_english",
    "bill_longTitleGa" : "bill_long_title_irish"
}

members_drop_cols = [
            'member_memberships_0_membership_represents_0_represent_representType',
            'member_uri', 
            'member_wikiTitle', 
            'member_memberships_0_membership_committees_0_uri',
            'member_memberships_0_membership_committees_0_houseNo',
            'member_memberships_0_membership_committees_0_houseCode',
            'member_memberships_0_membership_committees_2_uri',
            'member_memberships_0_membership_committees_1_houseNo',
            'member_memberships_0_membership_represents_0_represent_uri',
            'member_memberships_0_membership_uri',
            'member_memberships_0_membership_house_uri',
            'member_memberships_0_membership_committees_3_uri',
            'member_memberships_0_membership_committees_4_uri',
            'member_memberships_0_membership_parties_1_party_uri',
            'member_memberships_0_membership_parties_2_party_uri',
            'member_memberships_0_membership_parties_2_party_uri',
            'member_memberships_0_membership_committees_5_uri',
            'member_memberships_0_membership_committees_11_uri',
            'member_memberships_0_membership_committees_1_uri',
            'member_memberships_0_membership_committees_2_role',
            'member_memberships_0_membership_committees_4_role',
            'member_memberships_0_membership_committees_5_role',
            'member_memberships_0_membership_committees_6_uri',
            'member_memberships_0_membership_committees_7_uri',
            'member_memberships_0_membership_committees_8_uri',
            'member_memberships_0_membership_offices_5_office_officeName_uri',
            'member_memberships_0_membership_offices_4_office_officeName_uri',
            'member_memberships_0_membership_committees_9_uri',
            'member_memberships_0_membership_committees_10_uri',
            'member_image',
            'member_memberships_0_membership_committees_3_role',
            'member_memberships_0_membership_committees_1_houseCode',
            'member_memberships_0_membership_committees_1_role',
            'member_memberships_0_membership_committees_0_role',
            'member_showAs',
            'member_memberships_0_membership_dateRange_start',
            'member_memberships_0_membership_offices',
            'member_memberships_0_membership_parties_0_party_dateRange_start',
            'member_pId',
            'member_memberships_0_membership_committees',
            'member_gender',
            'member_memberships_0_membership_parties_0_party_uri',
            'member_memberships_0_membership_parties_0_party_partyCode',
            'member_memberships_0_membership_parties_0_party_dateRange_end'
            ]



members_rename = {
        'member_memberCode': 'unique_member_code',
        'member_memberships_0_membership_committees_0_mainStatus': 'committee_role',
        'member_memberships_0_membership_parties_0_party_showAs': 'party',
        # 'member_memberships_0_membership_committees_3_role': 'committee_role_"_title',
        'member_memberships_0_membership_committees_1_role_title': 'committee_role_1_title',
        'member_memberships_0_membership_represents_0_represent_representCode' : 'member_constituency',
        'member_memberships_0_membership_represents_0_represent_showAs': 'member_constiuency_no_dash',
        # 'member_memberships_0_membership_committees_0_committeeName_1_nameEn': 'committee_1_name_english_alt_CHECK',
        'member_memberships_0_membership_house_showAs' : 'dail_term',
        'member_memberships_0_membership_offices_0_office_officeName_showAs': 'ministerial_office',
        'member_memberships_0_membership_committees_0_committeeName_0_nameEn' : 'committee_1_name_english',
        'member_memberships_0_membership_committees_1_committeeName_0_nameEn':  'committee_2_name_english',
        'member_memberships_0_membership_committees_1_committeeName_0_dateRange_start': 'committee_2_start_date',
        # 'member_memberships_0_membership_committees_1_committeeDateRange_start': 'committee_2_start_date',
        'member_memberships_0_membership_committees_1_expiryType': 'committee_2_standing_order_type',
        'member_memberships_0_membership_committees_1_committeeName_0_dateRange_end': 'committee_2_end_date',
        'member_memberships_0_membership_committees_1_committeeID': 'committee_2_id',
        'member_memberships_0_membership_committees_0_committeeName_0_nameGa':  'committee_1_name_irish',
        'member_memberships_0_membership_committees_1_committeeName_0_nameGa':  'committee_2_name_irish',
        # 'member_memberships_0_membership_committees_0_committeeName_1_nameEn': 
        'member_memberships_0_membership_committees_3_committeeName_0_nameEn': 'committee_4_name_english',
        'member_memberships_0_membership_committees_3_committeeName_0_nameGa': 'committee_4_name_irish',
        'member_memberships_0_membership_committees_3_committeeID': 'committee_4_id',
        'member_memberships_0_membership_committees_3_committeeType_0': 'committee_4_type',
        'member_memberships_0_membership_committees_3_committeeDateRange_start': 'committee_4_start_date',
        'member_memberships_0_membership_committees_3_memberDateRange_start': 'committee_4_member_start_date',
        'member_memberships_0_membership_committees_3_memberDateRange_end': 'committee_4_member_end_date',
        'member_memberships_0_membership_committees_3_mainStatus': 'committee_4_main_status',
        'member_memberships_0_membership_committees_3_expiryType': 'committee_4_standing_order_type',
        'member_memberships_0_membership_committees_2_serviceUnit': 'committee_3_service_unit',
        'member_memberships_0_membership_committees_2_committeeType_0': 'committee_3_type',
        'member_memberships_0_membership_committees_2_committeeName_0_dateRange_end': 'committee_3_end_date',
        'member_memberships_0_membership_committees_3_committeeName_0_dateRange_start': 'committee_4_start_date',
        'member_memberships_0_membership_committees_3_committeeCode': 'committee_4_code',
        'member_memberships_0_membership_committees_3_status': 'committee_4_status',
        'member_memberships_0_membership_committees_3_committeeDateRange_end': 'committee_4_end_date',
        'member_memberships_0_membership_committees_3_committeeName_0_dateRange_end': 'committee_4_end_date',
        'member_memberships_0_membership_committees_4_memberDateRange_start': 'committee_5_start_date',
        'member_memberships_0_membership_committees_4_memberDateRange_end': 'committee_5_end_date',
        'member_memberships_0_membership_committees_4_committeeName_0_nameEn': 'committee_5_name_english',
        'member_memberships_0_membership_committees_4_mainStatus': 'committee_5_role',
        'member_memberships_0_membership_committees_4_serviceUnit': 'committee_5_service_unit',
        'member_memberships_0_membership_committees_4_committeeName_0_dateRange_start': 'committee_5_start_date',
        'member_memberships_0_membership_committees_4_committeeName_0_dateRange_end': 'committee_5_end_date',
        'member_memberships_0_membership_committees_4_committeeID': 'committee_5_id',
        'member_memberships_0_membership_committees_4_committeeCode': 'committee_5_code',
        'member_memberships_0_membership_committees_4_expiryType': 'committee_5_standing_order_type',
        'member_memberships_0_membership_committees_4_committeeType_0': 'committee_5_type',
        'member_memberships_0_membership_committees_4_committeeName_0_nameGa': 'committee_5_name_irish',
        'member_memberships_0_membership_committees_2_committeeName_0_nameEn': 'committee_3_name_english',
        'member_memberships_0_membership_committees_3_serviceUnit': 'committee_4_service_unit',
        'member_memberships_0_membership_committees_2_committeeName_0_dateRange_start': 'committee_3_start_date',
        'member_memberships_0_membership_committees_2_committeeName_0_nameGa': 'committee_3_name_irish',
        'member_memberships_0_membership_committees_4_status': 'committee_5_status',
        'member_memberships_0_membership_committees_2_expiryType': 'committee_3_standing_order_type',
        'member_memberships_0_membership_committees_2_committeeID': 'committee_3_id',
        'member_memberships_0_membership_committees_2_committeeCode': 'committee_3_code',
        'member_memberships_0_membership_committees_2_committeeDateRange_start': 'committee_3_start_date',
        'member_memberships_0_membership_committees_2_committeeDateRange_end': 'committee_3_end_date',
        'member_memberships_0_membership_committees_2_status': 'committee_3_status',
        'member_memberships_0_membership_house_houseCode': 'dail_code',
        'member_memberships_0_membership_committees_1_committeeType_0': 'committee_type_2',
        'member_memberships_0_membership_committees_0_committeeDateRange_start': 'committee_1_start_date',
        'member_memberships_0_membership_committees_0_committeeCode': 'committee_1_code',
        'member_memberships_0_membership_committees_0_committeeType_0': 'committee_1_type',
        'member_memberships_0_membership_committees_1_status': 'committee_2_status',
        'member_memberships_0_membership_committees_1_mainStatus': 'committee_2_main_status',
        'member_memberships_0_membership_committees_1_serviceUnit': 'committee_2_service_unit',        'member_memberships_0_membership_committees_1_committeeCode': 'committee_2_code',        'member_memberships_0_membership_committees_0_committeeDateRange_end' : 'committee_1_end_date',
        'member_memberships_0_membership_committees_0_expiryType' : 'committee_1_standing_order_type',
        'member_memberships_0_membership_house_houseNo' : 'dail_number',
        'member_memberships_0_membership_committees_5_committeeName_0_nameEn': 'committee_6_name_english',
        'member_memberships_0_membership_committees_5_committeeName_0_nameGa': 'committee_6_name_irish',
        'member_memberships_0_membership_committees_5_committeeID': 'committee_6_id',
        'member_memberships_0_membership_committees_5_expiryType': 'committee_6_standing_order_type',
        'member_memberships_0_membership_committees_5_committeeDateRange_start': 'committee_6_start_date',
        'member_memberships_0_membership_committees_5_committeeDateRange_end': 'committee_6_end_date',
        'member_memberships_0_membership_committees_5_status': 'committee_6_status',
        'member_memberships_0_membership_committees_5_committeeCode': 'committee_6_code',
        'member_memberships_0_membership_committees_5_committeeType_0': 'committee_6_type',
        'member_fullName': 'full_name',
        'member_firstName': 'first_name', 
        'member_lastName': 'last_name',
        
        # ========== COPILOT AUTO-RENAMED COLUMNS ==========
        # Committees 0-1: Alternate committee names (committeeName_1)
        'member_memberships_0_membership_committees_0_committeeName_1_nameGa': 'committee_1_name_irish_alt_copilot',
        'member_memberships_0_membership_committees_0_committeeName_1_dateRange_start': 'committee_1_alt_start_date_copilot',
        'member_memberships_0_membership_committees_0_committeeName_1_dateRange_end': 'committee_1_alt_end_date_copilot',
        'member_memberships_0_membership_committees_0_committeeName_1_nameEn': 'committee_1_name_english_alt_copilot',
        'member_memberships_0_membership_committees_1_committeeName_1_nameGa': 'committee_2_name_irish_alt_copilot',
        'member_memberships_0_membership_committees_1_committeeName_1_dateRange_start': 'committee_2_alt_start_date_copilot',
        'member_memberships_0_membership_committees_1_committeeName_1_dateRange_end': 'committee_2_alt_end_date_copilot',
        'member_memberships_0_membership_committees_1_committeeName_1_nameEn': 'committee_2_name_english_alt_copilot',
        
        # Committees 3,5-11: Additional committee details
        'member_memberships_0_membership_committees_3_committeeName_1_nameGa': 'committee_4_name_irish_alt_copilot',
        'member_memberships_0_membership_committees_3_committeeName_1_dateRange_start': 'committee_4_alt_start_date_copilot',
        'member_memberships_0_membership_committees_3_committeeName_1_dateRange_end': 'committee_4_alt_end_date_copilot',
        'member_memberships_0_membership_committees_3_committeeName_1_nameEn': 'committee_4_name_english_alt_copilot',
        'member_memberships_0_membership_committees_5_committeeName_1_nameGa': 'committee_6_name_irish_alt_copilot',
        'member_memberships_0_membership_committees_5_committeeName_1_dateRange_start': 'committee_6_alt_start_date_copilot',
        'member_memberships_0_membership_committees_5_committeeName_1_dateRange_end': 'committee_6_alt_end_date_copilot',
        'member_memberships_0_membership_committees_5_committeeName_1_nameEn': 'committee_6_name_english_alt_copilot',
        
        # Committees 6-11: Full details
        'member_memberships_0_membership_committees_6_mainStatus': 'committee_7_main_status_copilot',
        'member_memberships_0_membership_committees_6_status': 'committee_7_status_copilot',
        'member_memberships_0_membership_committees_6_committeeType_0': 'committee_7_type_copilot',
        'member_memberships_0_membership_committees_6_committeeCode': 'committee_7_code_copilot',
        'member_memberships_0_membership_committees_6_committeeName_0_nameGa': 'committee_7_name_irish_copilot',
        'member_memberships_0_membership_committees_6_committeeName_0_dateRange_start': 'committee_7_start_date_copilot',
        'member_memberships_0_membership_committees_6_committeeName_0_dateRange_end': 'committee_7_end_date_copilot',
        'member_memberships_0_membership_committees_6_committeeName_0_nameEn': 'committee_7_name_english_copilot',
        'member_memberships_0_membership_committees_6_serviceUnit': 'committee_7_service_unit_copilot',
        'member_memberships_0_membership_committees_6_committeeID': 'committee_7_id_copilot',
        'member_memberships_0_membership_committees_6_memberDateRange_start': 'committee_7_member_start_date_copilot',
        'member_memberships_0_membership_committees_6_memberDateRange_end': 'committee_7_member_end_date_copilot',
        'member_memberships_0_membership_committees_6_committeeDateRange_start': 'committee_7_committee_start_date_copilot',
        'member_memberships_0_membership_committees_6_committeeDateRange_end': 'committee_7_committee_end_date_copilot',
        'member_memberships_0_membership_committees_6_expiryType': 'committee_7_expiry_type_copilot',
        'member_memberships_0_membership_committees_6_role': 'committee_7_role_copilot',
        'member_memberships_0_membership_committees_6_role_dateRange_start': 'committee_7_role_start_date_copilot',
        'member_memberships_0_membership_committees_6_role_dateRange_end': 'committee_7_role_end_date_copilot',
        'member_memberships_0_membership_committees_6_role_title': 'committee_7_role_title_copilot',
        
        'member_memberships_0_membership_committees_7_mainStatus': 'committee_8_main_status_copilot',
        'member_memberships_0_membership_committees_7_status': 'committee_8_status_copilot',
        'member_memberships_0_membership_committees_7_committeeType_0': 'committee_8_type_copilot',
        'member_memberships_0_membership_committees_7_committeeCode': 'committee_8_code_copilot',
        'member_memberships_0_membership_committees_7_committeeName_0_nameGa': 'committee_8_name_irish_copilot',
        'member_memberships_0_membership_committees_7_committeeName_0_dateRange_start': 'committee_8_start_date_copilot',
        'member_memberships_0_membership_committees_7_committeeName_0_dateRange_end': 'committee_8_end_date_copilot',
        'member_memberships_0_membership_committees_7_committeeName_0_nameEn': 'committee_8_name_english_copilot',
        'member_memberships_0_membership_committees_7_serviceUnit': 'committee_8_service_unit_copilot',
        'member_memberships_0_membership_committees_7_committeeID': 'committee_8_id_copilot',
        'member_memberships_0_membership_committees_7_memberDateRange_start': 'committee_8_member_start_date_copilot',
        'member_memberships_0_membership_committees_7_memberDateRange_end': 'committee_8_member_end_date_copilot',
        'member_memberships_0_membership_committees_7_committeeDateRange_start': 'committee_8_committee_start_date_copilot',
        'member_memberships_0_membership_committees_7_committeeDateRange_end': 'committee_8_committee_end_date_copilot',
        'member_memberships_0_membership_committees_7_expiryType': 'committee_8_expiry_type_copilot',
        'member_memberships_0_membership_committees_7_role': 'committee_8_role_copilot',
        'member_memberships_0_membership_committees_7_role_dateRange_start': 'committee_8_role_start_date_copilot',
        'member_memberships_0_membership_committees_7_role_dateRange_end': 'committee_8_role_end_date_copilot',
        'member_memberships_0_membership_committees_7_role_title': 'committee_8_role_title_copilot',
        'member_memberships_0_membership_committees_7_committeeName_1_nameGa': 'committee_8_name_irish_alt_copilot',
        'member_memberships_0_membership_committees_7_committeeName_1_dateRange_start': 'committee_8_alt_start_date_copilot',
        'member_memberships_0_membership_committees_7_committeeName_1_dateRange_end': 'committee_8_alt_end_date_copilot',
        'member_memberships_0_membership_committees_7_committeeName_1_nameEn': 'committee_8_name_english_alt_copilot',
        
        'member_memberships_0_membership_committees_8_mainStatus': 'committee_9_main_status_copilot',
        'member_memberships_0_membership_committees_8_status': 'committee_9_status_copilot',
        'member_memberships_0_membership_committees_8_committeeType_0': 'committee_9_type_copilot',
        'member_memberships_0_membership_committees_8_committeeCode': 'committee_9_code_copilot',
        'member_memberships_0_membership_committees_8_committeeName_0_nameGa': 'committee_9_name_irish_copilot',
        'member_memberships_0_membership_committees_8_committeeName_0_dateRange_start': 'committee_9_start_date_copilot',
        'member_memberships_0_membership_committees_8_committeeName_0_dateRange_end': 'committee_9_end_date_copilot',
        'member_memberships_0_membership_committees_8_committeeName_0_nameEn': 'committee_9_name_english_copilot',
        'member_memberships_0_membership_committees_8_serviceUnit': 'committee_9_service_unit_copilot',
        'member_memberships_0_membership_committees_8_committeeID': 'committee_9_id_copilot',
        'member_memberships_0_membership_committees_8_memberDateRange_start': 'committee_9_member_start_date_copilot',
        'member_memberships_0_membership_committees_8_memberDateRange_end': 'committee_9_member_end_date_copilot',
        'member_memberships_0_membership_committees_8_committeeDateRange_start': 'committee_9_committee_start_date_copilot',
        'member_memberships_0_membership_committees_8_committeeDateRange_end': 'committee_9_committee_end_date_copilot',
        'member_memberships_0_membership_committees_8_expiryType': 'committee_9_expiry_type_copilot',
        'member_memberships_0_membership_committees_8_role': 'committee_9_role_copilot',
        
        'member_memberships_0_membership_committees_9_mainStatus': 'committee_10_main_status_copilot',
        'member_memberships_0_membership_committees_9_status': 'committee_10_status_copilot',
        'member_memberships_0_membership_committees_9_committeeType_0': 'committee_10_type_copilot',
        'member_memberships_0_membership_committees_9_committeeCode': 'committee_10_code_copilot',
        'member_memberships_0_membership_committees_9_committeeName_0_nameGa': 'committee_10_name_irish_copilot',
        'member_memberships_0_membership_committees_9_committeeName_0_dateRange_start': 'committee_10_start_date_copilot',
        'member_memberships_0_membership_committees_9_committeeName_0_dateRange_end': 'committee_10_end_date_copilot',
        'member_memberships_0_membership_committees_9_committeeName_0_nameEn': 'committee_10_name_english_copilot',
        'member_memberships_0_membership_committees_9_serviceUnit': 'committee_10_service_unit_copilot',
        'member_memberships_0_membership_committees_9_committeeID': 'committee_10_id_copilot',
        'member_memberships_0_membership_committees_9_memberDateRange_start': 'committee_10_member_start_date_copilot',
        'member_memberships_0_membership_committees_9_memberDateRange_end': 'committee_10_member_end_date_copilot',
        'member_memberships_0_membership_committees_9_committeeDateRange_start': 'committee_10_committee_start_date_copilot',
        'member_memberships_0_membership_committees_9_committeeDateRange_end': 'committee_10_committee_end_date_copilot',
        'member_memberships_0_membership_committees_9_expiryType': 'committee_10_expiry_type_copilot',
        'member_memberships_0_membership_committees_9_role': 'committee_10_role_copilot',
        
        'member_memberships_0_membership_committees_10_mainStatus': 'committee_11_main_status_copilot',
        'member_memberships_0_membership_committees_10_status': 'committee_11_status_copilot',
        'member_memberships_0_membership_committees_10_committeeType_0': 'committee_11_type_copilot',
        'member_memberships_0_membership_committees_10_committeeCode': 'committee_11_code_copilot',
        'member_memberships_0_membership_committees_10_committeeName_0_nameGa': 'committee_11_name_irish_copilot',
        'member_memberships_0_membership_committees_10_committeeName_0_dateRange_start': 'committee_11_start_date_copilot',
        'member_memberships_0_membership_committees_10_committeeName_0_dateRange_end': 'committee_11_end_date_copilot',
        'member_memberships_0_membership_committees_10_committeeName_0_nameEn': 'committee_11_name_english_copilot',
        'member_memberships_0_membership_committees_10_serviceUnit': 'committee_11_service_unit_copilot',
        'member_memberships_0_membership_committees_10_committeeID': 'committee_11_id_copilot',
        'member_memberships_0_membership_committees_10_memberDateRange_start': 'committee_11_member_start_date_copilot',
        'member_memberships_0_membership_committees_10_memberDateRange_end': 'committee_11_member_end_date_copilot',
        'member_memberships_0_membership_committees_10_committeeDateRange_start': 'committee_11_committee_start_date_copilot',
        'member_memberships_0_membership_committees_10_committeeDateRange_end': 'committee_11_committee_end_date_copilot',
        'member_memberships_0_membership_committees_10_expiryType': 'committee_11_expiry_type_copilot',
        'member_memberships_0_membership_committees_10_role': 'committee_11_role_copilot',
        
        'member_memberships_0_membership_committees_11_mainStatus': 'committee_12_main_status_copilot',
        'member_memberships_0_membership_committees_11_status': 'committee_12_status_copilot',
        'member_memberships_0_membership_committees_11_committeeType_0': 'committee_12_type_copilot',
        'member_memberships_0_membership_committees_11_committeeCode': 'committee_12_code_copilot',
        'member_memberships_0_membership_committees_11_committeeName_0_nameGa': 'committee_12_name_irish_copilot',
        'member_memberships_0_membership_committees_11_committeeName_0_dateRange_start': 'committee_12_start_date_copilot',
        'member_memberships_0_membership_committees_11_committeeName_0_dateRange_end': 'committee_12_end_date_copilot',
        'member_memberships_0_membership_committees_11_committeeName_0_nameEn': 'committee_12_name_english_copilot',
        'member_memberships_0_membership_committees_11_serviceUnit': 'committee_12_service_unit_copilot',
        'member_memberships_0_membership_committees_11_committeeID': 'committee_12_id_copilot',
        'member_memberships_0_membership_committees_11_memberDateRange_start': 'committee_12_member_start_date_copilot',
        'member_memberships_0_membership_committees_11_memberDateRange_end': 'committee_12_member_end_date_copilot',
        'member_memberships_0_membership_committees_11_committeeDateRange_start': 'committee_12_committee_start_date_copilot',
        'member_memberships_0_membership_committees_11_committeeDateRange_end': 'committee_12_committee_end_date_copilot',
        'member_memberships_0_membership_committees_11_expiryType': 'committee_12_expiry_type_copilot',
        'member_memberships_0_membership_committees_11_role': 'committee_12_role_copilot',
        'member_memberships_0_membership_committees_11_role_dateRange_start': 'committee_12_role_start_date_copilot',
        'member_memberships_0_membership_committees_11_role_dateRange_end': 'committee_12_role_end_date_copilot',
        'member_memberships_0_membership_committees_11_role_title': 'committee_12_role_title_copilot',
        
        # Additional committee role details
        'member_memberships_0_membership_committees_0_role_dateRange_start': 'committee_1_role_start_date_copilot',
        'member_memberships_0_membership_committees_0_role_dateRange_end': 'committee_1_role_end_date_copilot',
        'member_memberships_0_membership_committees_0_role_title': 'committee_1_role_title_copilot',
        'member_memberships_0_membership_committees_1_role_dateRange_start': 'committee_2_role_start_date_copilot',
        'member_memberships_0_membership_committees_1_role_dateRange_end': 'committee_2_role_end_date_copilot',
        'member_memberships_0_membership_committees_2_role_dateRange_start': 'committee_3_role_start_date_copilot',
        'member_memberships_0_membership_committees_2_role_dateRange_end': 'committee_3_role_end_date_copilot',
        'member_memberships_0_membership_committees_2_role_title': 'committee_3_role_title_copilot',
        'member_memberships_0_membership_committees_3_role_dateRange_start': 'committee_4_role_start_date_copilot',
        'member_memberships_0_membership_committees_3_role_dateRange_end': 'committee_4_role_end_date_copilot',
        'member_memberships_0_membership_committees_3_role_title': 'committee_4_role_title_copilot',
        'member_memberships_0_membership_committees_4_role_dateRange_start': 'committee_5_role_start_date_copilot',
        'member_memberships_0_membership_committees_4_role_dateRange_end': 'committee_5_role_end_date_copilot',
        'member_memberships_0_membership_committees_4_role_title': 'committee_5_role_title_copilot',
        
        # Offices
        'member_memberships_0_membership_offices_0_office_officeName_uri': 'office_0_name_uri_copilot',
        'member_memberships_0_membership_offices_0_office_dateRange_start': 'office_0_start_date_copilot',
        'member_memberships_0_membership_offices_0_office_dateRange_end': 'office_0_end_date_copilot',
        'member_memberships_0_membership_offices_1_office_officeName_uri': 'office_1_name_uri_copilot',
        'member_memberships_0_membership_offices_1_office_officeName_showAs': 'office_1_name_copilot',
        'member_memberships_0_membership_offices_1_office_dateRange_start': 'office_1_start_date_copilot',
        'member_memberships_0_membership_offices_1_office_dateRange_end': 'office_1_end_date_copilot',
        'member_memberships_0_membership_offices_2_office_officeName_uri': 'office_2_name_uri_copilot',
        'member_memberships_0_membership_offices_2_office_officeName_showAs': 'office_2_name_copilot',
        'member_memberships_0_membership_offices_2_office_dateRange_start': 'office_2_start_date_copilot',
        'member_memberships_0_membership_offices_2_office_dateRange_end': 'office_2_end_date_copilot',
        'member_memberships_0_membership_offices_3_office_officeName_uri': 'office_3_name_uri_copilot',
        'member_memberships_0_membership_offices_3_office_officeName_showAs': 'office_3_name_copilot',
        'member_memberships_0_membership_offices_3_office_dateRange_start': 'office_3_start_date_copilot',
        'member_memberships_0_membership_offices_3_office_dateRange_end': 'office_3_end_date_copilot',
        'member_memberships_0_membership_offices_4_office_officeName_showAs': 'office_4_name_copilot',
        'member_memberships_0_membership_offices_4_office_dateRange_start': 'office_4_start_date_copilot',
        'member_memberships_0_membership_offices_4_office_dateRange_end': 'office_4_end_date_copilot',
        'member_memberships_0_membership_offices_5_office_officeName_showAs': 'office_5_name_copilot',
        'member_memberships_0_membership_offices_5_office_dateRange_start': 'office_5_start_date_copilot',
        'member_memberships_0_membership_offices_5_office_dateRange_end': 'office_5_end_date_copilot',
        
        # Parties (alternate records)
        'member_memberships_0_membership_parties_1_party_showAs': 'party_1_name_copilot',
        'member_memberships_0_membership_parties_1_party_dateRange_start': 'party_1_start_date_copilot',
        'member_memberships_0_membership_parties_1_party_dateRange_end': 'party_1_end_date_copilot',
        'member_memberships_0_membership_parties_1_party_partyCode': 'party_1_code_copilot',
        'member_memberships_0_membership_parties_2_party_showAs': 'party_2_name_copilot',
        'member_memberships_0_membership_parties_2_party_dateRange_start': 'party_2_start_date_copilot',
        'member_memberships_0_membership_parties_2_party_dateRange_end': 'party_2_end_date_copilot',
        'member_memberships_0_membership_parties_2_party_partyCode': 'party_2_code_copilot',
        
        # House chamber/membership details
        'member_memberships_0_membership_house_chamberType': 'dail_chamber_type_copilot',
        'member_memberships_0_membership_memberDateRange_end': 'membership_end_date_copilot',
        'member_dateOfDeath': 'date_of_death_copilot',
        }

lobbying_rename = {
    "Id" :"primary_key", 
    "Url" : "lobby_enterprise_uri",
    "Lobbyist Name" : "lobbyist_name",
    "Date Published" : "date_published_timestamp",
    "Period" : "lobbying_period",
    "DPOs Lobbied" : "dpo_lobbied",
		"Relevant Matter" : "relevant_matter",
		"Public Policy Area" : "public_policy_area",
    "Specific Details" : "specific_details",
    "Intended Results" : "intended_results",
    "Lobbying Activities" : "lobbying_activities",
    "Person primarily responsible for lobbying on this activity" : "person_primarily_responsible",
    "Any DPOs or Former DPOs who carried out lobbying activities" : "dpos_or_former_dpos_who_carried_out_lobbying",
    "Current or Former DPOs" : "current_or_former_dpos",    
    "Was this a grassroots campaign?" : "was_this_a_grassroots_campaign",
    "Grassroots directive" : "grassroots_directive",
    "Was this lobbying done on behalf of a client?" : "was_this_lobbying_done_on_behalf_of_a_client",
    "Client(s)" : "clients"
    }