enrich_cols_to_select = ['join_key',
                  'unique_member_code',
                  'party', 
                  'first_name', 
                  'last_name', 
                  'member_constituency', 
                  'dail_term', 
                  'ministerial_office',
                  'committee_1_name_english',
                  'member_memberships_0_membership_committees_0_status',
                #   'committee_1_name_irish',
                  'committee_2_name_english',
                  'committee_2_status',
                  'committee_3_name_english',
                  'committee_3_status',
                  'committee_4_name_english',
                  'committee_4_status',
                  'committee_5_name_english',
                  'committee_5_status',
                #   'committee_4_service_unit'
                  ]


bill_cols_to_drop = [
    "bill_amendmentLists",
    "bill_act",
    "bill_billTypeURI",
    "bill_debates_0_chamber_uri",
    "bill_debates_0_debateSectionId",
    "bill_debates_0_uri",
    "bill_stages_0_event_chamber_uri",
    "bill_debates_1_chamber_uri",
    "bill_debates_2_chamber_uri",
    "bill_amendmentLists_5_amendmentList_chamber_uri",
    "bill_events_3_event_chamber_uri",
    "bill_stages_0_event_house_uri",
    "bill_debates_11_chamber_uri",
    "bill_debates_12_chamber_uri",
    "bill_stages_1_event_chamber_uri",
    "bill_amendmentLists_4_amendmentList_chamber_uri",
    "bill_debates_10_chamber_uri",
    "bill_amendmentLists_0_amendmentList_chamber_uri",
    "bill_amendmentLists_1_amendmentList_chamber_uri",
    "bill_amendmentLists_2_amendmentList_chamber_uri",
    "bill_amendmentLists_3_amendmentList_chamber_uri",
    "bill_stages_2_event_chamber_uri",
    "bill_stages_4_event_chamber_uri",
    "bill_debates_9_chamber_uri",
    "bill_debates_8_chamber_uri",
    "bill_debates_7_chamber_uri",
    "bill_debates_6_chamber_uri",
    "bill_debates_5_chamber_uri",
    "bill_debates_4_chamber_uri",
    "bill_debates_3_chamber_uri",
    "bill_events_0_event_chamber_chamberCode",
    "bill_events_0_event_chamber_showAs",
    "bill_events_0_event_chamber_uri",
    "bill_stages_2_event_house_uri",
    "bill_events_1_event_chamber_chamberCode",
    "bill_mostRecentStage_event_stageURI",
    "bill_mostRecentStage_event_uri",
    "bill_originHouse_uri",
    "bill_stages_9_event_house_uri",
    "bill_stages_8_event_house_uri",
    "bill_stages_3_event_house_uri",
    "bill_stages_1_event_house_uri",
    "bill_originHouseURI",
    "bill_sourceURI",
    "bill_sponsors_0_sponsor_as_showAs",
    "bill_versions_0_version_lang",
    "bill_versions_0_version_uri",
    "bill_stages_7_event_house_uri",
    "bill_debates_10_chamber_uri",
    "bill_stages_9_event_chamber_uri",
    "bill_events_2_event_chamber_uri",
    "bill_events_3_event_chamber_uri",
    "bill_events_1_event_chamber_uri",
    "bill_mostRecentStage_event_chamber_uri",
    "bill_debates_11_chamber_uri",
    "bill_debates_12_chamber_uri",
    "bill_stages_3_event_chamber_uri",
    "bill_stages_4_event_house_uri",
    "bill_stages_5_event_chamber_uri",
    "bill_stages_5_event_house_uri",
    "bill_stages_6_event_chamber_uri",
    "bill_stages_6_event_house_uri",
    "bill_stages_7_event_chamber_uri",
    "bill_stages_8_event_chamber_uri",
    "bill_events_0_event_eventURI",
    "bill_events_0_event_uri",
    "bill_events_1_event_eventURI",
    "bill_events_1_event_uri",
    "bill_methodURI",
    "bill_mostRecentStage_event_house_uri",
    "bill_stages_0_event_house_chamberCode",
    "bill_stages_0_event_house_chamberType",
    "bill_stages_0_event_house_houseCode",
    "bill_mostRecentStage_event_house_uri",
    "bill_relatedDocs_0_relatedDoc_lang",
    "bill_relatedDocs_0_relatedDoc_uri",
    "bill_sponsors_0_sponsor_as_uri",
    "bill_stages_0_event_stageURI",
    "bill_stages_0_event_uri",
    "bill_statusURI",
    "bill_versions_0_version_formats_xml",
    "bill_sponsors_2_sponsor_as_showAs",
    "bill_sponsors_2_sponsor_as_uri",
    "bill_sponsors_3_sponsor_as_showAs",
    "bill_sponsors_3_sponsor_as_uri",
    "bill_relatedDocs_0_relatedDoc_formats_xml"
]

bill_rename = {
    "bill_debates_0_chamber_showAs" : "bill_chamber",
    "bill_debates_0_date" : "bill_debates_date",
    "bill_debates_0_showAs" : "bill_debate_stages",
    "bill_events_0_event_chamber_showAs" : "bill_event_chamber",
    "bill_mostRecentStage_event_stageCompleted" : "bill_enacted",
    "bill_mostRecentStage_event_stageOutcome" : "bill_final_status",
    "bill_shortTitleEn" : "bill_short_title_en",
    "bill_shortTitleGa" : "bill_short_title_irish",
    "bill_sponsors_0_sponsor_by_showAs" : "bill_sponsor",
    "bill_sponsors_0_sponsor_by_uri" : "unique_member_code_raw",
    "bill_sponsors_0_sponsor_isPrimary" : "bill_primary_sponsor",
    "billSort_billShortTitleEnSort" : "bill_short_dash_title_en",
    "billSort_billShortTitleGaSort" : "bill_short_dash_title_irish",
    "billSort_billYearSort" : "bill_year",
    "bill_relatedDocs_0_relatedDoc_formats_pdf_uri" : "bill_related_doc_pdf",
    "bill_relatedDocs_0_relatedDoc_showAs" : "bill_related_doc_type",
    "bill_act_statutebookURI" : "bill_statue_book_link",
    "bill_billNo" : "bill_number",
    "bill_billYear" : "bill_year",
    "bill_lastUpdated" : "bill_date_last_updated",
    "bill_longTitleEn" : "bill_long_title_english",
    "bill_longTitleGa" : "bill_long_title_irish"
}

members_drop_cols = [
            'member_memberships_0_membership_represents_0_represent_representType',
            'member_uri', 
            'member_wikiTitle', 
            'member_memberships_0_membership_committees_0_uri',
            'member_memberships_0_membership_committees_0_houseNo',
            'member_memberships_0_membership_committees_0_houseCode',
            'member_memberships_0_membership_committees_2_uri',
            'member_memberships_0_membership_committees_1_houseNo',
            'member_memberships_0_membership_represents_0_represent_uri',
            'member_memberships_0_membership_uri',
            'member_memberships_0_membership_house_uri',
            'member_memberships_0_membership_committees_3_uri',
            'member_memberships_0_membership_committees_4_uri',
            'member_memberships_0_membership_parties_1_party_uri',
            'member_memberships_0_membership_parties_2_party_uri',
            'member_memberships_0_membership_parties_2_party_uri',
            'member_memberships_0_membership_committees_5_uri',
            'member_memberships_0_membership_committees_11_uri',
            'member_memberships_0_membership_committees_1_uri',
            'member_memberships_0_membership_committees_2_role',
            'member_memberships_0_membership_committees_4_role',
            'member_memberships_0_membership_committees_5_role',
            'member_memberships_0_membership_committees_6_uri',
            'member_memberships_0_membership_committees_7_uri',
            'member_memberships_0_membership_committees_8_uri',
            'member_memberships_0_membership_offices_5_office_officeName_uri',
            'member_memberships_0_membership_offices_4_office_officeName_uri',
            'member_memberships_0_membership_committees_9_uri',
            'member_memberships_0_membership_committees_10_uri',
            'member_image',
            'member_memberships_0_membership_committees_3_role',
            'member_memberships_0_membership_committees_1_houseCode',
            'member_memberships_0_membership_committees_1_role',
            'member_memberships_0_membership_committees_0_role',
            'member_showAs',
            'member_memberships_0_membership_dateRange_start',
            'member_memberships_0_membership_offices',
            'member_memberships_0_membership_parties_0_party_dateRange_start',
            'member_pId',
            'member_memberships_0_membership_committees',
            'member_gender',
            'member_memberships_0_membership_parties_0_party_uri',
            'member_memberships_0_membership_parties_0_party_partyCode',
            'member_memberships_0_membership_parties_0_party_dateRange_end'
            ]



members_rename = {
        'member_memberCode': 'unique_member_code',
        'member_memberships_0_membership_committees_0_mainStatus': 'committee_role',
        'member_memberships_0_membership_parties_0_party_showAs': 'party',
        # 'member_memberships_0_membership_committees_3_role': 'committee_role_"_title',
        'member_memberships_0_membership_committees_1_role_title': 'committee_role_1_title',
        'member_memberships_0_membership_represents_0_represent_representCode' : 'member_constituency',
        'member_memberships_0_membership_represents_0_represent_showAs': 'member_constiuency_no_dash',
        # 'member_memberships_0_membership_committees_0_committeeName_1_nameEn': 'committee_1_name_english_alt_CHECK',
        'member_memberships_0_membership_house_showAs' : 'dail_term',
        'member_memberships_0_membership_offices_0_office_officeName_showAs': 'ministerial_office',
        'member_memberships_0_membership_committees_0_committeeName_0_nameEn' : 'committee_1_name_english',
        'member_memberships_0_membership_committees_1_committeeName_0_nameEn':  'committee_2_name_english',
        'member_memberships_0_membership_committees_1_committeeName_0_dateRange_start': 'committee_2_start_date',
        # 'member_memberships_0_membership_committees_1_committeeDateRange_start': 'committee_2_start_date',
        'member_memberships_0_membership_committees_1_expiryType': 'committee_2_standing_order_type',
        'member_memberships_0_membership_committees_1_committeeName_0_dateRange_end': 'committee_2_end_date',
        'member_memberships_0_membership_committees_1_committeeID': 'committee_2_id',
        'member_memberships_0_membership_committees_0_committeeName_0_nameGa':  'committee_1_name_irish',
        'member_memberships_0_membership_committees_1_committeeName_0_nameGa':  'committee_2_name_irish',
        # 'member_memberships_0_membership_committees_0_committeeName_1_nameEn': 
        'member_memberships_0_membership_committees_3_committeeName_0_nameEn': 'committee_4_name_english',
        'member_memberships_0_membership_committees_3_committeeName_0_nameGa': 'committee_4_name_irish',
        'member_memberships_0_membership_committees_3_committeeID': 'committee_4_id',
        'member_memberships_0_membership_committees_3_committeeType_0': 'committee_4_type',
        'member_memberships_0_membership_committees_3_committeeDateRange_start': 'committee_4_start_date',
        'member_memberships_0_membership_committees_3_memberDateRange_start': 'committee_4_member_start_date',
        'member_memberships_0_membership_committees_3_memberDateRange_end': 'committee_4_member_end_date',
        'member_memberships_0_membership_committees_3_mainStatus': 'committee_4_main_status',
        'member_memberships_0_membership_committees_3_expiryType': 'committee_4_standing_order_type',
        'member_memberships_0_membership_committees_2_serviceUnit': 'committee_3_service_unit',
        'member_memberships_0_membership_committees_2_committeeType_0': 'committee_3_type',
        'member_memberships_0_membership_committees_2_committeeName_0_dateRange_end': 'committee_3_end_date',
        'member_memberships_0_membership_committees_3_committeeName_0_dateRange_start': 'committee_4_start_date',
        'member_memberships_0_membership_committees_3_committeeCode': 'committee_4_code',
        'member_memberships_0_membership_committees_3_status': 'committee_4_status',
        'member_memberships_0_membership_committees_3_committeeDateRange_end': 'committee_4_end_date',
        'member_memberships_0_membership_committees_3_committeeName_0_dateRange_end': 'committee_4_end_date',
        'member_memberships_0_membership_committees_4_memberDateRange_start': 'committee_5_start_date',
        'member_memberships_0_membership_committees_4_memberDateRange_end': 'committee_5_end_date',
        'member_memberships_0_membership_committees_4_committeeName_0_nameEn': 'committee_5_name_english',
        'member_memberships_0_membership_committees_4_mainStatus': 'committee_5_role',
        'member_memberships_0_membership_committees_4_serviceUnit': 'committee_5_service_unit',
        'member_memberships_0_membership_committees_4_committeeName_0_dateRange_start': 'committee_5_start_date',
        'member_memberships_0_membership_committees_4_committeeName_0_dateRange_end': 'committee_5_end_date',
        'member_memberships_0_membership_committees_4_committeeID': 'committee_5_id',
        'member_memberships_0_membership_committees_4_expiryType': 'committee_5_standing_order_type',
        'member_memberships_0_membership_committees_4_committeeType_0': 'committee_5_type',
        'member_memberships_0_membership_committees_4_committeeName_0_nameGa': 'committee_5_name_irish',
        'member_memberships_0_membership_committees_2_committeeName_0_nameEn': 'committee_3_name_english',
        'member_memberships_0_membership_committees_3_serviceUnit': 'committee_4_service_unit',
        'member_memberships_0_membership_committees_2_committeeName_0_dateRange_start': 'committee_3_start_date',
        'member_memberships_0_membership_committees_2_committeeName_0_nameGa': 'committee_3_name_irish',
        'member_memberships_0_membership_committees_4_status': 'committee_5_status',
        'member_memberships_0_membership_committees_2_expiryType': 'committee_3_standing_order_type',
        'member_memberships_0_membership_committees_2_committeeID': 'committee_3_id',
        'member_memberships_0_membership_committees_2_committeeDateRange_start': 'committee_3_start_date',
        'member_memberships_0_membership_committees_2_committeeDateRange_end': 'committee_3_end_date',
        'member_memberships_0_membership_committees_2_status': 'committee_3_status',
        'member_memberships_0_membership_house_houseCode': 'dail_code',
        'member_memberships_0_membership_committees_1_committeeType_0': 'committee_type_2',
        'member_memberships_0_membership_committees_0_committeeDateRange_start': 'committee_1_start_date',
        'member_memberships_0_membership_committees_0_committeeCode': 'committee_1_code',
        'member_memberships_0_membership_committees_0_committeeType_0': 'committee_1_type',
        'member_memberships_0_membership_committees_1_status': 'committee_2_status',
        'member_memberships_0_membership_committees_1_mainStatus': 'committee_2_main_status',
        'member_memberships_0_membership_committees_1_serviceUnit': 'committee_2_service_unit',
        'member_memberships_0_membership_committees_0_committeeDateRange_end' : 'committee_1_end_date',
        'member_memberships_0_membership_committees_0_expiryType' : 'committee_1_standing_order_type',
        'member_memberships_0_membership_house_houseNo' : 'dail_number',
        'member_memberships_0_membership_committees_5_committeeName_0_nameEn': 'committee_6_name_english',
        'member_memberships_0_membership_committees_5_committeeName_0_nameGa': 'committee_6_name_irish',
        'member_memberships_0_membership_committees_5_committeeID': 'committee_6_id',
        'member_memberships_0_membership_committees_5_expiryType': 'committee_6_standing_order_type',
        'member_memberships_0_membership_committees_5_committeeDateRange_start': 'committee_6_start_date',
        'member_memberships_0_membership_committees_5_committeeDateRange_end': 'committee_6_end_date',
        'member_memberships_0_membership_committees_5_status': 'committee_6_status',
        'member_memberships_0_membership_committees_5_committeeCode': 'committee_6_code',
        'member_memberships_0_membership_committees_5_committeeType_0': 'committee_6_type',
        'member_fullName': 'full_name',
        'member_firstName': 'first_name', 
        'member_lastName': 'last_name'
        }