"""Shared UI components for Dáil Tracker Streamlit pages (v5).

Package split (2026-07, C4 of doc/REFACTORING_CANDIDATES.md) of the former
single ``ui/components.py`` (2,155 lines) into submodules by concern:
``text`` (search/normalise), ``lifecycle`` (``dt_page`` + boot/boundary),
``layout`` (year selector, cards, hero), ``narrative`` (findings-lede,
evidence strips, callouts), ``navigation`` (TD jump/search, filter bar,
breadcrumb, pill), ``cards`` (member/party/committee card builders),
``pagination`` (stat fragments, profile header, sidebar pickers, pager) and
``support`` (the /support page + app footer). Every name the old flat module
exposed is re-exported here unchanged, so ``from ui.components import X``
keeps working across every page that consumes this module.
"""

from __future__ import annotations

from .cards import (  # noqa: F401
    PARTY_COLOURS,
    committee_identity_strip,
    committee_row_html,
    find_a_td_filter,
    find_a_td_search,
    member_card_html,
    party_colour,
    party_stripe_html,
    proportion_stripe_html,
    rank_card_row,
    ranked_member_card,
)
from .layout import (  # noqa: F401
    card_row,
    hero_banner,
    info_card,
    render_notable_chips,
    year_selector,
)
from .lifecycle import (  # noqa: F401
    dt_page,
    fmt_civic_date,
    hide_sidebar,
    page_error_boundary,
    period_year_pills,
)
from .narrative import (  # noqa: F401
    back_button,
    card_sources_html,
    empty_state,
    evidence_heading,
    finding_lede,
    glossary_strip,
    member_moved_callout,
    outcome_badge,
    render_national_finance_context,
    stat_strip,
    subsection_heading,
    todo_callout,
    totals_strip,
)
from .navigation import (  # noqa: F401
    PILL_VARIANTS,
    breadcrumb,
    field_label,
    filter_bar,
    main_member_jump,
    member_jump_panel,
    pill,
)
from .pagination import (  # noqa: F401
    clickable_card_link,
    interest_declaration_item,
    member_profile_header,
    nav_button,
    paginate,
    pagination_controls,
    render_stat_strip,
    sidebar_date_range,
    sidebar_member_filter,
    stat_item,
)
from .support import (  # noqa: F401
    _CORRECTION_BODY,
    coffee_button_html,
    coffee_url,
    contact_email,
    site_footer_html,
    support_ask_html,
    support_costs_html,
    support_help_html,
    support_hero_html,
    support_honesty_html,
    support_page_html,
)
from .text import (  # noqa: F401
    clean_meta,
    search_matches,
    search_normalise,
    text_search_mask,
)

__all__ = [
    "PARTY_COLOURS",
    "PILL_VARIANTS",
    "_CORRECTION_BODY",
    "back_button",
    "breadcrumb",
    "card_row",
    "card_sources_html",
    "clean_meta",
    "clickable_card_link",
    "coffee_button_html",
    "coffee_url",
    "committee_identity_strip",
    "committee_row_html",
    "contact_email",
    "dt_page",
    "empty_state",
    "evidence_heading",
    "field_label",
    "filter_bar",
    "find_a_td_filter",
    "find_a_td_search",
    "finding_lede",
    "fmt_civic_date",
    "glossary_strip",
    "hero_banner",
    "hide_sidebar",
    "info_card",
    "interest_declaration_item",
    "main_member_jump",
    "member_card_html",
    "member_jump_panel",
    "member_moved_callout",
    "member_profile_header",
    "nav_button",
    "outcome_badge",
    "page_error_boundary",
    "paginate",
    "pagination_controls",
    "party_colour",
    "party_stripe_html",
    "period_year_pills",
    "pill",
    "proportion_stripe_html",
    "rank_card_row",
    "ranked_member_card",
    "render_national_finance_context",
    "render_notable_chips",
    "render_stat_strip",
    "search_matches",
    "search_normalise",
    "sidebar_date_range",
    "sidebar_member_filter",
    "site_footer_html",
    "stat_item",
    "stat_strip",
    "subsection_heading",
    "support_ask_html",
    "support_costs_html",
    "support_help_html",
    "support_hero_html",
    "support_honesty_html",
    "support_page_html",
    "text_search_mask",
    "todo_callout",
    "totals_strip",
    "year_selector",
]
