#!/usr/bin/env python
"""Generate doc/INDEX.md from the doc/ tree — a token-cheap map so agents can
pick the right doc without reading (or grepping) every file.

The index is GENERATED, so it cannot rot: run it after adding/renaming/retiring
a doc. CI can enforce freshness with `--check` (non-zero exit if stale).

For each doc it reports: title, tier/status/domain/key (from YAML front-matter
if present), size in KB and estimated tokens, and last-updated date. Docs with
no front-matter are listed under "unclassified" so the backlog is visible rather
than hidden.

    python tools/build_doc_index.py            # rewrite doc/INDEX.md
    python tools/build_doc_index.py --check     # exit 1 if INDEX.md is stale
"""

from __future__ import annotations

import re
import sys
from datetime import date
from pathlib import Path

DOC_DIR = Path(__file__).resolve().parent.parent / "doc"
INDEX = DOC_DIR / "INDEX.md"
FM_KEYS = ("tier", "status", "domain", "updated", "read_when", "key", "superseded_by")


def read_text(p: Path) -> str:
    return open(p, encoding="utf-8", errors="replace").read()


def parse_front_matter(text: str) -> dict[str, str]:
    """Return the YAML front-matter as a flat str->str dict (only FM_KEYS)."""
    if not text.startswith("---"):
        return {}
    end = text.find("\n---", 3)
    if end == -1:
        return {}
    block = text[3:end]
    out: dict[str, str] = {}
    for line in block.splitlines():
        m = re.match(r"^([a-z_]+):\s*(.*)$", line.strip())
        if m and m.group(1) in FM_KEYS:
            out[m.group(1)] = m.group(2).strip()
    return out


def first_heading(text: str) -> str:
    for line in text.splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return ""


def collect() -> list[dict]:
    rows = []
    paths = [p for p in sorted(DOC_DIR.glob("*.md")) if p.name != INDEX.name]

    # Archived documents are deliberately outside the active root, but a
    # document explicitly marked stale/superseded remains discoverable here.
    # Older, unclassified archive material stays out of the working index.
    for p in sorted((DOC_DIR / "archive").glob("*.md")):
        fm = parse_front_matter(read_text(p))
        if fm.get("status", "").upper() in ("SUPERSEDED", "STALE"):
            paths.append(p)

    for p in paths:
        text = read_text(p)
        fm = parse_front_matter(text)
        nbytes = len(text.encode("utf-8"))
        rows.append(
            {
                "name": p.name,
                "path": p.relative_to(DOC_DIR).as_posix(),
                "title": first_heading(text) or p.stem.replace("_", " ").title(),
                "tier": fm.get("tier", ""),
                "status": fm.get("status", ""),
                "domain": fm.get("domain", ""),
                "updated": fm.get("updated", ""),
                "read_when": fm.get("read_when", ""),
                "superseded_by": fm.get("superseded_by", ""),
                "kb": round(nbytes / 1024),
                "tok": round(nbytes / 4 / 1000, 1),  # ~4 bytes/token, in thousands
            }
        )
    return rows


def status_rank(status: str) -> int:
    return {"LIVE": 0, "": 1, "STALE": 2, "SUPERSEDED": 3}.get(status.upper(), 1)


def render(rows: list[dict]) -> str:
    live = [r for r in rows if r["status"].upper() == "LIVE"]
    superseded = [r for r in rows if r["status"].upper() in ("SUPERSEDED", "STALE")]
    unclassified = [r for r in rows if not r["status"]]
    total_tok = round(sum(r["tok"] for r in rows), 1)

    out: list[str] = []
    out.append("<!-- GENERATED by tools/build_doc_index.py — do not edit by hand. -->")
    out.append("<!-- Run: python tools/build_doc_index.py   (CI: --check) -->")
    out.append("")
    out.append("# doc/ index")
    out.append("")
    out.append(
        f"{len(rows)} docs · ~{total_tok}k tokens total · "
        f"{len(live)} LIVE · {len(superseded)} superseded/stale · "
        f"{len(unclassified)} unclassified. "
        "**Never read a doc whole to find out if it's relevant — scan this table, "
        "then open with `offset`/`limit` or grep the `key:` line.**"
    )
    out.append("")

    def table(title: str, group: list[dict], note: str = "") -> None:
        if not group:
            return
        out.append(f"## {title}")
        if note:
            out.append(note)
        out.append("")
        out.append("| doc | domain | ~tok | updated | read when |")
        out.append("|---|---|---:|---|---|")
        for r in sorted(group, key=lambda x: (x["domain"], x["name"])):
            rw = r["read_when"] or (f"→ {r['superseded_by']}" if r["superseded_by"] else "")
            rw = rw.replace("|", "\\|")
            out.append(
                f"| [{r['name']}]({r['path']}) | {r['domain'] or '—'} | {r['tok']}k | {r['updated'] or '—'} | {rw} |"
            )
        out.append("")

    table("LIVE", live)
    table(
        "Archived superseded / stale",
        superseded,
        "> Kept in [archive/](archive/) for history and inbound references. Do not rely on their bodies.",
    )
    table(
        "Unclassified (no front-matter yet)",
        unclassified,
        "> Backlog: add the 7-line front-matter block (tier/status/domain/updated/"
        "supersedes/read_when/key) so these move into the tables above.",
    )
    out.append(f"<!-- generated {date.today().isoformat()} -->")
    out.append("")
    return "\n".join(out)


def main() -> int:
    rows = collect()
    content = render(rows)
    check = "--check" in sys.argv
    if check:
        current = read_text(INDEX) if INDEX.exists() else ""

        # ignore the trailing generated-date line when comparing
        def strip(s: str) -> str:
            return re.sub(r"<!-- generated .* -->", "", s).strip()

        if strip(current) != strip(content):
            print("doc/INDEX.md is STALE — run: python tools/build_doc_index.py")
            return 1
        print("doc/INDEX.md is up to date.")
        return 0
    with open(INDEX, "w", encoding="utf-8") as fh:
        fh.write(content)
    print(f"Wrote {INDEX} ({len(rows)} docs).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
