#!/usr/bin/env python
"""Check pyproject → uv.lock → runtime requirements parity without rewriting files."""

from __future__ import annotations

import difflib
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def normalized_export(text: str) -> list[str]:
    lines = text.replace("\r\n", "\n").splitlines()
    if lines[:1] == ["# This file was autogenerated by uv via the following command:"]:
        return lines[2:]
    return lines


def main() -> int:
    uv = shutil.which("uv")
    if not uv:
        print("FAIL  uv is not on PATH")
        return 1

    locked = subprocess.run(
        [uv, "lock", "--check"],
        cwd=ROOT,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
    )
    if locked.returncode:
        print((locked.stderr or locked.stdout).strip())
        print("FAIL  uv.lock is not in sync with pyproject.toml")
        return locked.returncode

    with tempfile.TemporaryDirectory() as directory:
        exported = Path(directory) / "requirements.txt"
        result = subprocess.run(
            [
                uv,
                "export",
                "--frozen",
                "--no-hashes",
                "--no-emit-project",
                "--no-default-groups",
                "-o",
                str(exported),
            ],
            cwd=ROOT,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
        )
        if result.returncode or not exported.exists():
            print((result.stderr or result.stdout).strip())
            print("FAIL  uv could not export the locked runtime requirements")
            return result.returncode or 1
        actual = normalized_export(exported.read_text(encoding="utf-8"))

    expected = normalized_export((ROOT / "requirements.txt").read_text(encoding="utf-8"))
    if actual != expected:
        diff = list(
            difflib.unified_diff(
                expected,
                actual,
                fromfile="requirements.txt",
                tofile="uv export",
                lineterm="",
            )
        )
        for line in diff[:80]:
            print(line)
        if len(diff) > 80:
            print(f"... {len(diff) - 80} more diff lines")
        print("FAIL  requirements.txt is not the current app-runtime export of uv.lock")
        return 1

    print("OK — pyproject.toml, uv.lock, and requirements.txt are in sync.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
