"""
pq_nonanswer_breakdown.py — profile the NON-answers in the full PQ corpus.

Read-only exploration over data/_sandbox/pq_disclosures_full.parquet. A
"non-answer" = a reply to a question that SOUGHT data but did NOT disclose any
(no euro figure, no table). We taxonomise those non-answers so we know what is
actually in the corpus before committing to any entity join.

Counts are on DISTINCT REPLIES (dedupe on answer_text): grouped questions share
one answer, and refusals cluster on heavily-grouped controversial topics, so
row-level counts inflate (the transparency-report lesson).

    python -m pipeline_sandbox.pq_disclosures.pq_nonanswer_breakdown \
        --in data/_sandbox/pq_disclosures_full.parquet

Writes a markdown breakdown next to the module and prints a summary.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

import pandas as pd

from pipeline_sandbox.pq_disclosures.pq_answer_mine_experimental import classify

_OUT_MD = Path(__file__).with_name("NONANSWER_BREAKDOWN.md")

# Same withholding/deflection vocabulary the classifier uses, re-described here
# for the human-readable taxonomy.
_GROUND_LABEL = {
    "not_held_centrally": "Data not held / not collated centrally",
    "commercial_sensitivity": "Commercially sensitive / commercial confidence",
    "not_published": "Department does not publish it",
    "data_protection": "Withheld on data-protection / GDPR grounds",
    "privacy_safety": "Withheld to protect privacy / safety / identity",
    "disproportionate_cost": "Would take a disproportionate amount of time/cost",
    "would_prejudice": "Would prejudice the State / negotiations / outcome",
}


def _excerpt(s: str, n: int = 260) -> str:
    s = re.sub(r"\s+", " ", str(s or "")).strip()
    return (s[:n] + "…") if len(s) > n else s


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--in", dest="inp",
                    default="data/_sandbox/pq_disclosures_full.parquet")
    ap.add_argument("--examples", type=int, default=3,
                    help="example replies to show per category")
    args = ap.parse_args(argv)

    df = pd.read_parquet(args.inp)
    n_rows = len(df)

    # --- distinct replies: one row per unique answer_text -------------------
    # Keep the first row of each answer group; carry its question/department.
    reps = df.drop_duplicates(subset=["answer_text"]).copy()
    n_reps = len(reps)

    # Re-apply the CURRENT classifier (analysis layer) rather than trusting the
    # columns baked into the parquet at mine time — lets us iterate the
    # deflection/refusal taxonomy without re-mining 221k sections. Caveat: runs
    # over the stored answer_text (truncated to 6000 chars at parse), but
    # referral/refusal phrasing sits near the top of a reply, so truncation
    # rarely changes the label.
    _cls = reps.apply(
        lambda r: classify(r["question_text"], r["answer_text"]),
        axis=1, result_type="expand",
    )
    for col in ("data_sought", "discloses", "is_refusal", "refusal_type",
                "is_deflection"):
        reps[col] = _cls[col]

    # --- the data-seeking denominator --------------------------------------
    seek = reps[reps["data_sought"]].copy()
    n_seek = len(seek)

    disclosed = seek[seek["discloses"]]
    nonans = seek[~seek["discloses"]].copy()  # data sought, nothing disclosed
    n_non = len(nonans)

    # --- taxonomy of the non-answers ---------------------------------------
    # Priority order: no-reply > explicit refusal > deflection > narrative-only.
    def bucket(r) -> str:
        if not r["has_reply"]:
            return "no_substantive_reply"
        if r["is_refusal"]:
            return f"refusal::{r['refusal_type']}"
        if r["is_deflection"]:
            return "deflection (agency's matter, e.g. 'matter for the HSE')"
        return "narrative_only (answered in prose, no figure/table)"

    nonans["bucket"] = nonans.apply(bucket, axis=1)
    counts = nonans["bucket"].value_counts()

    lines: list[str] = []
    P = lines.append
    P("# PQ corpus — what are the NON-answers?\n")
    P(f"_Source: `{args.inp}` · generated by pq_nonanswer_breakdown.py_\n")
    P("Counts are **distinct replies** (deduped on answer text) so grouped "
      "questions don't inflate.\n")
    P("> EXPERIMENTAL discovery artifact. The classifier is **re-applied at "
      "analysis time** (widened deflection/referral detector), not the columns "
      "baked into the parquet — so these counts can differ from the mine-time "
      "transparency report.\n")
    P("## Funnel\n")
    P(f"- **{n_rows:,}** question/answer rows")
    P(f"- **{n_reps:,}** distinct replies")
    P(f"- **{n_seek:,}** distinct replies to questions that SOUGHT data "
      f"(the denominator)")
    P(f"  - **{len(disclosed):,}** disclosed a figure/table "
      f"({100*len(disclosed)/n_seek:.1f}%)")
    P(f"  - **{n_non:,}** did NOT disclose — the non-answers "
      f"({100*n_non/n_seek:.1f}%)\n")

    P("## Non-answer taxonomy (of the "
      f"{n_non:,} data-seeking non-disclosing replies)\n")
    P("| category | replies | % of non-answers |")
    P("|---|--:|--:|")
    for b, c in counts.items():
        P(f"| {b} | {c:,} | {100*c/n_non:.1f}% |")
    P("")

    # explicit refusals only, with the human label + top depts + examples
    P("## Explicit refusals — grounds, departments, examples\n")
    refusals = nonans[nonans["is_refusal"]]
    if len(refusals):
        for ground, sub in sorted(
            refusals.groupby("refusal_type"),
            key=lambda kv: -len(kv[1]),
        ):
            label = _GROUND_LABEL.get(ground, ground)
            P(f"### {label}  — {len(sub):,} replies\n")
            topd = sub["department"].value_counts().head(5)
            P("Top departments: "
              + ", ".join(f"{d} ({n})" for d, n in topd.items()) + "\n")
            for _, r in sub.head(args.examples).iterrows():
                P(f"- **[{r['question_ref']}] {r['department']}** "
                  f"({r['date']})")
                P(f"  - Q: {_excerpt(r['question_text'], 200)}")
                P(f"  - A: {_excerpt(r['answer_text'], 320)}")
            P("")
    else:
        P("_none_\n")

    # deflections
    P("## Deflections (legitimately the agency's data) — examples\n")
    defl = nonans[nonans["bucket"].str.startswith("deflection")]
    P(f"{len(defl):,} replies. Top departments: "
      + ", ".join(f"{d} ({n})" for d, n in
                  defl["department"].value_counts().head(5).items()) + "\n")
    for _, r in defl.head(args.examples).iterrows():
        P(f"- **[{r['question_ref']}] {r['department']}** ({r['date']})")
        P(f"  - Q: {_excerpt(r['question_text'], 200)}")
        P(f"  - A: {_excerpt(r['answer_text'], 320)}")
    P("")

    # narrative-only — the big residual bucket; sample to characterise it
    P("## Narrative-only non-answers (the big residual) — examples\n")
    narr = nonans[nonans["bucket"].str.startswith("narrative_only")]
    P(f"{len(narr):,} replies — answered in prose with no figure or table. "
      "These are NOT necessarily evasive (many are genuine policy/status "
      "answers); sampling to see what they look like:\n")
    P("Top departments: "
      + ", ".join(f"{d} ({n})" for d, n in
                  narr["department"].value_counts().head(8).items()) + "\n")
    for _, r in narr.head(args.examples + 2).iterrows():
        P(f"- **[{r['question_ref']}] {r['department']}** ({r['date']})")
        P(f"  - Q: {_excerpt(r['question_text'], 180)}")
        P(f"  - A: {_excerpt(r['answer_text'], 300)}")
    P("")

    _OUT_MD.write_text("\n".join(lines), encoding="utf-8")

    # --- console summary (ASCII-safe) --------------------------------------
    print(f"rows={n_rows:,}  distinct_replies={n_reps:,}  "
          f"data_seeking={n_seek:,}")
    print(f"disclosed={len(disclosed):,} ({100*len(disclosed)/n_seek:.1f}%)  "
          f"non_answers={n_non:,} ({100*n_non/n_seek:.1f}%)")
    print("\nNON-ANSWER TAXONOMY (distinct replies):")
    for b, c in counts.items():
        print(f"  {100*c/n_non:5.1f}%  {c:6,}  {b}")
    print(f"\nwrote {_OUT_MD}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
