-- v_lobbying_contact_detail — one row per (politician, return, policy area)
-- Source: data/silver/lobbying/enriched/lobbying_contact_detail.parquet
-- Generated by pipeline_sandbox/lobbying_enrichment.py
-- Has source_url (real lobbying.ie URLs), public_policy_area, Date-typed period.
-- Supports all Stage 2 filters:
--   politician profile  → WHERE member_name = ?
--   org profile         → WHERE lobbyist_name = ?
--   area profile        → WHERE public_policy_area = ?
-- No JOINs — all join logic upstream in lobbying_enrichment.py.

CREATE OR REPLACE VIEW v_lobbying_contact_detail AS
SELECT
    primary_key                     AS return_id,
    full_name                       AS member_name,
    COALESCE(chamber,   '')         AS chamber,
    COALESCE(position,  '')         AS position,
    lobbyist_name,
    public_policy_area,
    lobbying_period_start_date::DATE AS period_start_date,
    source_url
FROM read_parquet('data/silver/lobbying/enriched/lobbying_contact_detail.parquet')
ORDER BY period_start_date DESC NULLS LAST;
