from __future__ import annotations

from tools.check_dependency_state import normalized_export


def test_normalized_export_ignores_only_the_uv_output_command():
    left = """# This file was autogenerated by uv via the following command:
#    uv export -o requirements.txt
package==1.0
"""
    right = """# This file was autogenerated by uv via the following command:
#    uv export -o C:/temp/requirements.txt
package==1.0
"""
    assert normalized_export(left) == normalized_export(right) == ["package==1.0"]


def test_normalized_export_keeps_non_generated_content():
    assert normalized_export("package==1.0\n") == ["package==1.0"]
